### ISSUE TITLE
Payment Tutorial

### ISSUE THREAD

**Issue by pmaojo** [tryshoppe/shoppe#107]
Hello, 

When I reached the payment tutorial on the webpage of tryshoppe I found that there is dummy text and I don´t know how to finish my app so it can do payments. Any tip?

Thankyouu

**Comment by mklb** [comment]
+1 
I have the same problem. Would love to see a Paypal module ,too.

**Comment by deanperry** [comment]
I've updated the docs on the site showing how to add Stripe - http://tryshoppe.com/docs/tutorials/payment-gateways

As for the PayPal module, when I get some time I will look into building this.
