### ISSUE TITLE
Email Templates

### ISSUE THREAD

**Issue by deanpcmad** [tryshoppe/shoppe#125]
It would be good if emails could be sent with email templates instead of using a plain email

**Comment by andretanguy** [comment]
+1

**Comment by notrab** [comment]
Have you managed to have a look at this yet @deanperry ? [Florrick](https://github.com/adamcooke/florrick) is a good solution for this.

Integrating a `EmailTemplate` model with the following attributes should cover it;

* Template Name
* Template Description
* Subject
* Body (florrick tags)
* Active (could be used at sending email level, if enabled, mailers send it)

**Comment by arturenault** [comment]
In the meantime is there a way to disable the emails that shoppe sends? I've written my own mailer so that I can use custom layouts but shoppe still sends its own emails, which is annoying to the customer.

**Comment by deanperry** [comment]
You can fork the gem and disable the areas where it sends email
