### ISSUE TITLE
Multiple Product Images

### ISSUE THREAD

**Issue by metabren** [tryshoppe/shoppe#129]
Is this on the agenda?  Would be great to have this and thumbnail versions of each image as well.

Also wondering why the nifty-attachments gem was used instead of using something like paperclip?

**Comment by deanperry** [comment]
I'm closing this Issue for the moment as this functionality will be part of attachments. Please see & comment on this PR #169 for more info

**Comment by dminchev** [comment]
@m-codebastards I'm unable to add cards to this Trello board.
> I've created trello board to put, discuss and vote all ideas. There is also column 'In progress' to see who is working on what. What do you think? https://trello.com/b/6ctllnYz/shoppe-core-development

+1 for carrierwave and multiple images per item

**Comment by neilb7** [comment]
has the multiple upload functionality been added now?
