### ISSUE TITLE
Despatch Note in shoppe admin

### ISSUE THREAD

**Issue by justinweathersby** [tryshoppe/shoppe#149]
Hey guys i just picked this gem up a few days ago. Im trying to update an old site using rails. Still fairly new to rails and extremely new to shoppe. I was wondering how i would go about altering the layout or at least information in the dispatch note under the admin section?

**Comment by adamcooke** [comment]
You can override any views you want to as per any Rails engine. However, please don't support support requests on here as this is designed for tracking bugs :smile:
