### ISSUE TITLE
Flexible & customisable order flow

### ISSUE THREAD

**Issue by dgolman** [tryshoppe/shoppe#151]
Flexible & customisable order flow is listed in the features and I would like to know where I can find documentation on how to extend Shoppe and customize the order flow. I have specific order "states" I would like to transition and order through.

**Comment by deanperry** [comment]
What sort of states would you have? This kind of thing would be down to your application because you would deal with the front end.

**Comment by twss** [comment]
I think the orders table would need to be polymorphic then, would it not, to accomodate this?

* Back-end `Shoppe::Order` class has its current set of key states.
* Front-end `MyShop::Order` inherits from `Shoppe::Order` and implements it's specific workflow additions.

This way the back-end can, without any knowledge of this custom workflow, still go about the general processing of orders.

**Comment by deanperry** [comment]
An Order has a `properties` option so when updating the order in your front end, you could set the status that way?

```ruby
@order = Shoppe::Order.first
@order.properties["status"] = "started"
@order.save
```

You can set as many properties as you need.

```ruby
@order.properties["foo"] = "bar"
@order.properties["bar"] = "foo"

@order.properties  #=>  {"foo"=>"bar", "bar"=>"foo"}
```

How does that work for you? Also, apologies for the delay in replying to your issue!

**Comment by deanperry** [comment]
I'm going to close this issue as I believe it has been answered.
