### ISSUE TITLE
ArgumentError: string contains null byte

### ISSUE THREAD

**Issue by kapilchoudhary** [tryshoppe/shoppe#155]
When i run rake shoppe:seed...........getting error

ArgumentError: string contains null byte
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/connection_adapters/postgresql/oid.rb:34:in `unescape_bytea'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/connection_adapters/postgresql/oid.rb:34:in `type_cast'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/connection_adapters/postgresql_adapter.rb:136:in `type_cast'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/attribute_methods/dirty.rb:93:in `_field_changed?'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/attribute_methods/dirty.rb:66:in `write_attribute'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/attribute_methods/write.rb:19:in `__temp__46164716='
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/nifty-attachments-1.0.3/lib/nifty/attachments/attachment.rb:29:in `block in <class:Attachment>'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:387:in `_run__815447992__validation__callbacks'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:80:in `run_callbacks'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activemodel-4.0.0/lib/active_model/validations/callbacks.rb:106:in `run_validations!'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activemodel-4.0.0/lib/active_model/validations.rb:314:in `valid?'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/validations.rb:70:in `valid?'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/validations.rb:77:in `perform_validations'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/validations.rb:51:in `save'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/attribute_methods/dirty.rb:32:in `save'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/transactions.rb:270:in `block (2 levels) in save'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/transactions.rb:326:in `block in with_transaction_returning_status'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:200:in `transaction'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/transactions.rb:209:in `transaction'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/transactions.rb:323:in `with_transaction_returning_status'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/transactions.rb:270:in `block in save'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/transactions.rb:281:in `rollback_active_record_state!'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/transactions.rb:269:in `save'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/associations/has_many_association.rb:39:in `insert_record'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/associations/collection_association.rb:463:in `block (2 levels) in create_record'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/associations/collection_association.rb:367:in `add_to_target'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/associations/collection_association.rb:461:in `block in create_record'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/associations/collection_association.rb:152:in `block in transaction'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:200:in `transaction'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/transactions.rb:209:in `transaction'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/associations/collection_association.rb:151:in `transaction'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/associations/collection_association.rb:460:in `create_record'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/associations/collection_association.rb:121:in `create'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/associations/collection_proxy.rb:260:in `create'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/nifty-attachments-1.0.3/lib/nifty/attachments/model_extension.rb:11:in `block (2 levels) in included'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/nifty-attachments-1.0.3/lib/nifty/attachments/model_extension.rb:9:in `each'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/nifty-attachments-1.0.3/lib/nifty/attachments/model_extension.rb:9:in `block in included'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:419:in `_run__542327534__save__callbacks'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:80:in `run_callbacks'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/callbacks.rb:299:in `create_or_update'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/persistence.rb:128:in `save!'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/validations.rb:57:in `save!'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/attribute_methods/dirty.rb:41:in `save!'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/transactions.rb:275:in `block in save!'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/transactions.rb:326:in `block in with_transaction_returning_status'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `block in transaction'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:210:in `within_new_transaction'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `transaction'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/transactions.rb:209:in `transaction'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/transactions.rb:323:in `with_transaction_returning_status'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activerecord-4.0.0/lib/active_record/transactions.rb:275:in `save!'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/shoppe-1.0.3/db/seeds.rb:35:in `<top (required)>'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `require'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `block in require'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:213:in `load_dependency'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `require'
/home/rails/.rvm/gems/ruby-2.1.0@milano/gems/shoppe-1.0.3/lib/tasks/shoppe.rake:4:in `block (2 levels) in <top (required)>'
/home/rails/.rvm/gems/ruby-2.1.0@milano/bin/ruby_executable_hooks:15:in `eval'

**Comment by adamcooke** [comment]
I'm afraid I can't replicate this. Please provide additional information about your environment or better steps to replicate. You may re-open if needed.

**Comment by hstove** [comment]
This happened to me too on a clean install. It happens when trying to create the first product:

~~~
Shoppe::Product Exists (0.9ms)  SELECT  1 AS one FROM "shoppe_products" WHERE "shoppe_products"."permalink" = 'yealink-t20p' LIMIT 1
  SQL (2.5ms)  INSERT INTO "shoppe_products" ("name", "sku", "description", "short_description", "weight", "price", "cost_price", "tax_rate_id", "featured", "product_category_id", "permalink", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13) RETURNING "id"  [["name", "Yealink T20P"], ["sku", "YL-SIP-T20P"], ["description", "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."], ["short_description", "If cheap & cheerful is what you’re after, the Yealink T20P is what you’re looking for."], ["weight", "1.119"], ["price", "54.99"], ["cost_price", "44.99"], ["tax_rate_id", 1], ["featured", "t"], ["product_category_id", 1], ["permalink", "yealink-t20p"], ["created_at", "2015-03-17 06:53:12.851229"], ["updated_at", "2015-03-17 06:53:12.851229"]]
   (0.5ms)  COMMIT
   (0.2ms)  BEGIN
  Shoppe::Product Exists (1.3ms)  SELECT  1 AS one FROM "shoppe_products" WHERE ("shoppe_products"."permalink" = 'yealink-t20p' AND "shoppe_products"."id" != 1) LIMIT 1
   (0.5ms)  SELECT "nifty_attachments"."id" FROM "nifty_attachments" WHERE "nifty_attachments"."parent_id" = $1 AND "nifty_attachments"."parent_type" = $2 AND "nifty_attachments"."role" = 'default_image'  [["parent_id", 1], ["parent_type", "Shoppe::Product"]]
   (0.2ms)  ROLLBACK
rake aborted!
ArgumentError: string contains null byte
-e:1:in `<main>'
Tasks: TOP => shoppe:seed
~~~

**Comment by deanperry** [comment]
Are you using Rails 4.2.0 and PostgreSQL? If so, it's a bug in Rails and
will be fixed in the latest version

**Comment by hstove** [comment]
Thanks! I updated to 4.2.1.rc4 and all is well.

**Comment by deanperry** [comment]
Good to hear!
