### ISSUE TITLE
State incompatibility with will_paginate due to kaminari in tutorial

### ISSUE THREAD

**Issue by jackregnart** [tryshoppe/shoppe#156]
If you have will_paginate in your Gemfile it will break the shoppe interface due to shoppe using kaminari.

Add the fact that happens to your tutorial/readme - or perhaps fix it somehow.

I'm mainly adding this issue because there wasn't one when I was trying to figure out what was causing the 500 and it might help other people.

**Comment by deanperry** [comment]
I can't seem to replicate this in a new Rails 4.2 app with the latest version of Shoppe & will_paginate so I'm going to close it for now. Feel free to re-open it if the issue persists.
