### ISSUE TITLE
No route for adding to basket from tutorial

### ISSUE THREAD

**Issue by cdesch** [tryshoppe/shoppe#158]
The [tutorial](http://tryshoppe.com/docs/tutorials/setting-up) doesn't mention a route to `post` for products when adding them to the basket. What is that route?

Here is my current `routes.rb` based on the tutorial. What is the post path? I've tried using the [shoppe-example](https://github.com/tryshoppe/shoppe-example) ones

	  mount Shoppe::Engine => "/shoppe"
	  get 'product/:permalink' => 'products#show', :as => 'product'
	  #root :to => 'products#index'
	  get 'store', :to => 'products#index'
	  get 'basket' => 'orders#show'
	  delete 'basket' => 'orders#destroy'
  

Also, the [API Docs](http://api.tryshoppe.com/) are not there 

Here is the error I get when Clicking "add to basket" for a seed product

	Started POST "/product/snom-870" for 127.0.0.1 at 2015-02-26 14:41:58 -0500

	ActionController::RoutingError (No route matches [POST] "/product/snom-870"):
	  web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:22:in `middleware_call'
	  web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:13:in `call'
	  newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	  actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
	  newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	  railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
	  railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
	  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
	  activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
	  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
	  railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
	  newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	  actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
	  newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	  rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
	  newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	  rack (1.6.0) lib/rack/runtime.rb:18:in `call'
	  newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	  activesupport (4.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
	  newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	  rack (1.6.0) lib/rack/lock.rb:17:in `call'
	  newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	  actionpack (4.2.0) lib/action_dispatch/middleware/static.rb:113:in `call'
	  newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	  rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
	  newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	  airbrake (4.1.0) lib/airbrake/user_informer.rb:16:in `_call'
	  airbrake (4.1.0) lib/airbrake/user_informer.rb:12:in `call'
	  newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	  railties (4.2.0) lib/rails/engine.rb:518:in `call'
	  railties (4.2.0) lib/rails/application.rb:164:in `call'
	  newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	  rack (1.6.0) lib/rack/content_length.rb:15:in `call'
	  thin (1.6.3) lib/thin/connection.rb:86:in `block in pre_process'
	  thin (1.6.3) lib/thin/connection.rb:84:in `catch'
	  thin (1.6.3) lib/thin/connection.rb:84:in `pre_process'
	  thin (1.6.3) lib/thin/connection.rb:53:in `process'
	  thin (1.6.3) lib/thin/connection.rb:39:in `receive_data'
	  eventmachine (1.0.7) lib/eventmachine.rb:187:in `run_machine'
	  eventmachine (1.0.7) lib/eventmachine.rb:187:in `run'
	  thin (1.6.3) lib/thin/backends/base.rb:73:in `start'
	  thin (1.6.3) lib/thin/server.rb:162:in `start'
	  rack (1.6.0) lib/rack/handler/thin.rb:19:in `run'
	  rack (1.6.0) lib/rack/server.rb:286:in `start'
	  railties (4.2.0) lib/rails/commands/server.rb:80:in `start'
	  railties (4.2.0) lib/rails/commands/commands_tasks.rb:80:in `block in server'
	  railties (4.2.0) lib/rails/commands/commands_tasks.rb:75:in `tap'
	  railties (4.2.0) lib/rails/commands/commands_tasks.rb:75:in `server'
	  railties (4.2.0) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	  railties (4.2.0) lib/rails/commands.rb:17:in `<top (required)>'
	  bin/rails:4:in `require'
	  bin/rails:4:in `<top (required)>'
	  -e:1:in `load'
	  -e:1:in `<main>'

**Comment by deanperry** [comment]
Hey, I'm going to be working on updating the documentation so expect to hear something either over the weekend or next week :)

**Comment by deanperry** [comment]
You should be able to use the example though as it is currently running at http://demo.tryshoppe.com/

**Comment by cdesch** [comment]
thanks, but thats the example I mentioned in my comment. It is out of date by at least a year.

**Comment by SkyKOG** [comment]
Hi @cdesch , 

I faced the same issue, so this is what worked.

route:
```
post 'buy/:permalink' => 'products#buy', :as => 'buy_product'
```

link in `products/show.html.haml`
```
= link_to "Add to basket", buy_product_path(@product.permalink), :method => :post
```

Hope this helps!

Regards

**Comment by 5sp4lr** [comment]
Thank you @SkyKOG  You just saved me ;_;

**Comment by SkyKOG** [comment]
@5sp4lr dont mention it :) :+1:

**Comment by deanperry** [comment]
The documentation on the site has now been updated :+1:  http://tryshoppe.com/docs/tutorials/setting-up
