### ISSUE TITLE
API Documentation link in Readme appears to be incorrect

### ISSUE THREAD

**Issue by bernsno** [tryshoppe/shoppe#159]
Hi gang,

_sorry this is being submitted as an issue, didn't see additional non-security contact info_

We're interested in working with Shoppe but the API docs appear to have gone missing: http://api.tryshoppe.com/

Additionally, some key docs on the site appear to be unfinished: http://tryshoppe.com/docs/tutorials/payment-gateways

Has the documentation moved elsewhere? I'm looking to better understand how you work with payment gateways and shipping providers.

Thanks!

**Comment by deanperry** [comment]
Hey, no worries.
@adamcooke would you be able to take a look at the api.tryshoppe.com issue as I don't have access to that?
As for the documentation, most of it could do with updating. If I get change over the weekend, I'll see if I can take a look at improving/re-writing it.

For payment gateways, we have a Stripe extension which can be found here - https://github.com/tryshoppe/shoppe-stripe

As for shipping providers, you can set the provider, tracking URL and different prices depending on weight and location.
Hope this helps so far.

**Comment by adamcooke** [comment]
I've fixed up api.tryshoppe.com :)

**Comment by deanperry** [comment]
I've added some documentation on adding Stripe to your Shoppe site - http://tryshoppe.com/docs/extending

**Comment by ceritium** [comment]
http://api.tryshoppe.com  do not display the documentation.
