### ISSUE TITLE
Product Reviews

### ISSUE THREAD

**Issue by fletcher890** [tryshoppe/shoppe#160]
I would like to work on adding product reviews into Shoppe, is this something that would benefit the project at this stage?

**Comment by deanperry** [comment]
Shoppe is designed to be light weight and simple to use hence it has the main features for an ecommerce store. You are free to fork the project and modify it for your own use however

**Comment by fletcher890** [comment]
I was actually looking to contribute to the shoppe project but if you don't think that it would be a beneficial feature then that is fair enough.

**Comment by deanperry** [comment]
Probably best bringing @adamcooke into the convo to answer that question as he is the guy who developed it. I'm mainly helping with issues, pull requests & some features

**Comment by adamcooke** [comment]
I think this is probably something which doesn't need to be within the Shoppe core and would be better implemented by either another module or within the store's app itself.

**Comment by craft37** [comment]
@adamcooke  You know, I think this feature so much important for eccomerce than email templates, for example.
When we are buying something - revews are important for sure.
So it's nonetheless needed, probably.
