### ISSUE TITLE
Noob help

### ISSUE THREAD

**Issue by 5sp4lr** [tryshoppe/shoppe#163]
Can anyone explain to me how I don't need to make a product Model for products to be saved into the database and whatnot.  I'm extreme confused. I follow the guide on adding products and I'm even more lost.

**Comment by deanperry** [comment]
Shoppe already has all the basic models required. To add a product you login to the admin panel (at `/shoppe` by default), go to products and create

**Comment by 5sp4lr** [comment]
@deanperry i keep getting an error when i try to add products that way

ArgumentError in Shoppe::ProductsController#create

string contains null byte

**Comment by deanperry** [comment]
What's your setup? What database are you using, SQLite, MySQL or PostgreSQL? Also what version of Ruby and also what version of Rails?



Dean Perry
Sent from Outlook on my iPhone 




On Sat, Mar 14, 2015 at 4:30 PM -0700, "5sp4lr" <notifications@github.com> wrote:












@deanperry i keep getting an error when i try to add products that way



ArgumentError in Shoppe::ProductsController#create



string contains null byte

**Comment by 5sp4lr** [comment]
database - postgresql
ruby version - 2.1.5
rails version -  4.0.1

**Comment by deanperry** [comment]
Ok. I'm not sure if Shoppe has been tested with PostgreSQL. It has been fully tested on MySQL however but I'll see if I can look into Postgres support. I don't have any experience with it so I'll have to get it installed first and play around with it. 


Dean Perry
Sent from Outlook on my iPhone 




On Sat, Mar 14, 2015 at 5:26 PM -0700, "5sp4lr" <notifications@github.com> wrote:












database - postgresql

ruby version - 2.1.5

rails version -  4.0.1

**Comment by 5sp4lr** [comment]
@deanperry  it appears that this error only comes up when i try to add an image with the product. :c

**Comment by deanperry** [comment]
Ah yes, I think that's one of the plugins we are using for image uploads

**Comment by deanperry** [comment]
I've had a look into this issue today and it's a bug in Rails 4.2.0.
It is fixed in Rails 4.2.1 (using 4.2.1.rc4 doesn't show the error) - https://github.com/rails/rails/pull/17680

**Comment by briandiaz** [comment]
@5sp4lr  is closed. :D
