### ISSUE TITLE
Add the ability to use S3 when uploading product images

### ISSUE THREAD

**Issue by deanperry** [tryshoppe/shoppe#168]
I'm thinking maybe give the user the option to choose what storage the product image uploader uses. Maybe this should be a separate module (`shoppe-s3`) or by adding Carrierwave?

**Comment by sjayanna** [comment]
This is helpful, we are looking at shoppe and this was one of the feature we will have to change in our codebase. Not sure if storing large data in db is a good idea.

**Comment by sjayanna** [comment]
@deanperry , do you know when you plan to implement this? Thanks!

**Comment by deanperry** [comment]
The project I'm using Shoppe on has been put on the back burner so I
haven't had chance to work on it yet but I'll see what I can do sometime
this week.
Thanks!

**Comment by sjayanna** [comment]
@deanperry  great thanks! maybe I can also help. Do you have a branch?

**Comment by deanperry** [comment]
Not yet. I'll try and get a basic gem created & uploaded to GitHub

**Comment by deanperry** [comment]
Now #211 has been merged, this is very easy as Shoppe now uses Carrierwave. I'll do add some documentation to the Shoppe site

**Comment by deanperry** [comment]
OK I've added some documentation - http://tryshoppe.com/docs/attachments
