### ISSUE TITLE
Setting up products on home page

### ISSUE THREAD

**Issue by 5sp4lr** [tryshoppe/shoppe#173]
I'm using bootstrap with shoppe so i did this in my home's index.html.erb

    <% @products.each do |category, products| %>
      <h3><%= category.name %></h3>
      <ul class="list-inline">
        <% products.each do |product| %>
    <div class="col-sm-4 col-lg-4 col-md-4">
                        <div class="thumbnail">
                             <%= image_tag product.default_image.path, :width => '320px', :height => '150px' %> 
                            <div class="caption">
                                <h4 class="pull-right"><%= number_to_currency product.price %></h4>
                                <h4><%= link_to product.name, product_path(product.permalink)%></a>
                                </h4>
                            </div>
                            <div class="ratings">
                                <p class="pull-right">15 reviews</p>
                                <p>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                </p>
                            </div>
                        </div>
                    </div>
                  <% end %>
                  <ul>
                  <% end %>

and now i get an action error 
    NoMethodError in Home#index
    Showing c:/Sites/shoppe/app/views/home/index.html.erb where line #48 raised:

undefined method `each' for nil:NilClass
Rails.root: c:/Sites/shoppe

I'm not sure what i should do because the models were not made in the newb friendly way i remember since i am using shoppe. HALP

P.S line 48 is  <% @products.each do |category, products| %>

**Comment by deanperry** [comment]
What code is in the controller index method?
Just a heads up, Shoppe hasn't been tested on Windows.

**Comment by 5sp4lr** [comment]
@deanperry 
   
      def index
    @products = Shoppe::Product.root.ordered.includes(:product_category, :variants)
    @products = @products.group_by(&:product_category)
      end

**Comment by 5sp4lr** [comment]
That is an issue here. I'm making an ecommerce website for a technical project in my college. I gotta pass it to graduate and i decided to use shoppe. But if i keep running into errors like this because of compatibility issues, i might be fkd :U

**Comment by 5sp4lr** [comment]
Alright i fixed the issue. After taking a long break and clearing my mind. (jk i was flipping going crazy)

i forgot to add the above index method into my home controller as well ;_:

#CLOSED
