### ISSUE TITLE
Shoppe on Heroku

### ISSUE THREAD

**Issue by 5sp4lr** [tryshoppe/shoppe#174]
So i pushed my app to heroku. It hasnt been fully developed but i wanted to check the compatibility.
So far everything works(by everything i mean the admin functionality)

http://zone-tag420.herokuapp.com/

Except I cannot add to basket

**Comment by deanperry** [comment]
I've personally not tested it on Heroku but it should all work ok. As for the add to basket issue, have you followed through the tutorial [here](http://tryshoppe.com/docs/tutorials/baskets)?

**Comment by 5sp4lr** [comment]
@deanperry Yes i followed the tutorial and everything works the app when i run the server locally but not on heroku.

**Comment by 5sp4lr** [comment]
@deanperry I have people working on it now. Its probably nothing big. I'll update you in the next few minutes. They say they fixed it.

**Comment by 5sp4lr** [comment]
@deanperry  There was a problem with the stock of the item. We added it in stock but the error was still present. After another commit and a push to heroku everything was fine.
