### ISSUE TITLE
B2C e-commerce

### ISSUE THREAD

**Issue by 5sp4lr** [tryshoppe/shoppe#176]
Let's say that hypothetically an e-commerce website is developed with shoppe, A business to consumer once at that. In the case where companies or organizations pay an amount of money to sell goods on the site, would shoppe allow that? Is there a way for you to add users as admins but remove certain privileges like tampering with products the MAIN user or the owner of the site has put?

I realize shoppe is for small shops and just a way to get set up quick, but i really like the idea you have going on here and i wanna put together a demo for a few lecturers with shoppe and  i would like to figure this out if it is possible.

**Comment by deanperry** [comment]
Yeah that should be doable using something like cancancan to set permissions
