### ISSUE TITLE
TypeError: Object doesn't support this property or method

### ISSUE THREAD

**Issue by mukulsaharia** [tryshoppe/shoppe#177]
http://localhost:3000/shoppe/login 

error occur
TypeError: Object doesn't support this property or method
in line : 
  = javascript_include_tag 'shoppe/application'
i think it is java scroipt error

**Comment by deanperry** [comment]
What version of Ruby, Rails & Shoppe are you using?

**Comment by mukulsaharia** [comment]
its
rails 4.1.0
ruby 2.0.0p195
Shoppe 1.0

**Comment by deanperry** [comment]
Can you try Shoppe 1.0.5?

**Comment by deanperry** [comment]
Also is this on a new rails app or existing? If existing can you supply
your gemfile

**Comment by mukulsaharia** [comment]
its a new application...

**Comment by deanperry** [comment]
Shoppe has been testing in both new 4.2.0 and 4.1.0 apps so there must be something you have installed that may be conflicting. Can you paste your Gemfile here please? Have you also tried updating to the latest version of Shoppe?

**Comment by twss** [comment]
I think this error usually happens when you don't have "therubyracer" gem (or an associated JS runtime installed, such as execjs or phantomjs)

Or something is up with your coffeescript.

**Comment by deanperry** [comment]
Yeah it could be that I suppose. What OS are you running it on? Having a quick Google, some people are having that issue trying to run Rails on Windows
