### ISSUE TITLE
Reg:- Can i use shoppe gem using rails application in production???

### ISSUE THREAD

**Issue by Ramesh-Palanivel** [tryshoppe/shoppe#178]
Hi! Thanks for implementing shoppe gem in rails applications..I am new developer for rails applications..
Here i did Rails application using "gem 'shoppe', '~> 1.0'" . now it's working good. but i am little afraid can i use this application in live productions mode. Please help me any one of this group.

Thanks in advance

**Comment by deanperry** [comment]
Shoppe is production ready. It's currently being used On this site with no
issues http://voipfront.co.uk

Is there any reason why you don't think it is ready for production?

On Wednesday, April 15, 2015, Ramesh-Palanivel <notifications@github.com>
wrote:

> Hi! Thanks for implementing shoppe gem in rails applications..I am new
> developer for rails applications..
> Here i did Rails application using "gem 'shoppe', '~> 1.0'" . now it's
> working good. but i am little afraid can i use this application in live
> productions mode. Please help me any one of this group.
>
> Thanks in advance
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tryshoppe/shoppe/issues/178>.
>


-- 
Sent from Gmail Mobile

**Comment by Ramesh-Palanivel** [comment]
@ deanperry , Thank you for your updates.
