### ISSUE TITLE
I unable to create new users.

### ISSUE THREAD

**Issue by Ramesh-Palanivel** [tryshoppe/shoppe#179]
Hi! Thank you for implementing shoppe gem in rails applications..I am new developer for rails applications..Here i did Rails application using "gem 'shoppe', '~> 1.0'" . Now it's working good.
Few queries about this.

i) I got error like below while creating new users. 
Also What purpose of "System Settings". how i can use system setting, Explain?

Error Message:-
translation missing: en.shoppe.shared.error_occured
You cannot make changes to users in demo mode. Sorry about that.

ii) How can i add one more functionality called manufacture of product. How can i add additional features in back end.

Please suggest me regarding above queries. 

Thanks in advance
Ramesh

**Comment by deanperry** [comment]
The demo mode is locked down. You'll need to disable demo mode in the settings to enable the extra features
