### ISSUE TITLE
Uncaught exception: undefined method `keys' for "translation missing: en.shoppe.settings.defaults":String

### ISSUE THREAD

**Issue by asvechkar** [tryshoppe/shoppe#182]
After include gems: 
gem "shoppe-stripe", require: "shoppe/stripe"
gem 'shoppe-paypal'

Rails can't run with exception "Uncaught exception: undefined method `keys' for "translation missing: en.shoppe.settings.defaults":String"

https://github.com/tryshoppe/shoppe/blob/master/lib/shoppe/settings.rb#L16

**Comment by asvechkar** [comment]
Method run before i18n load yml file

**Comment by asvechkar** [comment]
Full log:
Exiting
Uncaught exception: undefined method `keys' for "translation missing: en.shoppe.settings.defaults":String
	/Users/asvechkar/.rvm/gems/ruby-2.2.0/gems/shoppe-1.0.5/lib/shoppe/settings.rb:16:in `method_missing'
	/Users/asvechkar/.rvm/gems/ruby-2.2.0/gems/shoppe-paypal-1.0.0/lib/shoppe/paypal.rb:36:in `setup'
	/Users/asvechkar/.rvm/gems/ruby-2.2.0/gems/shoppe-paypal-1.0.0/lib/shoppe/paypal/engine.rb:6:in `block in <class:Engine>'
	/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
	/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
	/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
	/Users/asvechkar/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	/Users/asvechkar/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	/Users/asvechkar/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	/Users/asvechkar/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	/Users/asvechkar/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each'
	/Users/asvechkar/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `call'
	/Users/asvechkar/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	/Users/asvechkar/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	/Users/asvechkar/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
	/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
	/Users/asvechkar/Projects/project/config/environment.rb:5:in `<top (required)>'
	/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	/Users/asvechkar/Projects/project/config.ru:3:in `block in <main>'
	/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/rack-1.6.0/lib/rack/builder.rb:55:in `instance_eval'
	/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/rack-1.6.0/lib/rack/builder.rb:55:in `initialize'
	/Users/asvechkar/Projects/project/config.ru:in `new'
	/Users/asvechkar/Projects/project/config.ru:in `<main>'
	/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/rack-1.6.0/lib/rack/builder.rb:49:in `eval'
	/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/rack-1.6.0/lib/rack/builder.rb:49:in `new_from_string'
	/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/rack-1.6.0/lib/rack/builder.rb:40:in `parse_file'
	/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/rack-1.6.0/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/rack-1.6.0/lib/rack/server.rb:208:in `app'
	/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/commands/server.rb:61:in `app'
	/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/rack-1.6.0/lib/rack/server.rb:336:in `wrapped_app'
	/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/commands/server.rb:139:in `log_to_stdout'
	/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/commands/server.rb:78:in `start'
	/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in `tap'
	/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in `server'
	/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	/Users/asvechkar/Projects/project/bin/rails:8:in `require'
	/Users/asvechkar/Projects/project/bin/rails:8:in `<top (required)>'
	/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/ruby-debug-ide-0.4.28/bin/rdebug-ide:121:in `<top (required)>'

**Comment by deanperry** [comment]
Yep I'm still trying to diagnose why this is happening :/

On Thursday, April 30, 2015, Aleksey Svechkar <notifications@github.com>
wrote:

> Full log:
> Exiting
> Uncaught exception: undefined method keys' for "translation missing:
> en.shoppe.settings.defaults":String
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.0/gems/shoppe-1.0.5/lib/shoppe/settings.rb:16:in
> method_missing'
> /Users/asvechkar/.rvm/gems/ruby-2.2.0/gems/shoppe-paypal-1.0.0/lib/shoppe/paypal.rb:36:in
> setup'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.0/gems/shoppe-paypal-1.0.0/lib/shoppe/paypal/engine.rb:6:inblock
> in class:Engine'
> /Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/initializable.rb:30:in
> instance_exec'
> /Users/asvechkar/.rvm/gems/ruby-2.2.0@global
> /gems/railties-4.2.0/lib/rails/initializable.rb:30:inrun'
> /Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/initializable.rb:55:in
> block in run_initializers'
> /Users/asvechkar/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:226:inblock
> in tsort_each'
> /Users/asvechkar/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:348:in block
> (2 levels) in each_strongly_connected_component'
> /Users/asvechkar/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:429:in
> each_strongly_connected_component_from'
> /Users/asvechkar/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:347:in block
> in each_strongly_connected_component'
> /Users/asvechkar/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in
> each'
> /Users/asvechkar/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in
> call'
> /Users/asvechkar/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in
> each_strongly_connected_component'
> /Users/asvechkar/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:224:in
> tsort_each'
> /Users/asvechkar/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:203:in
> tsort_each'
> /Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/initializable.rb:54:in
> run_initializers'
> /Users/asvechkar/.rvm/gems/ruby-2.2.0@global
> /gems/railties-4.2.0/lib/rails/application.rb:352:ininitialize!'
> /Users/asvechkar/Projects/project/config/environment.rb:5:in <top
> (required)>'
> /Users/asvechkar/.rvm/gems/ruby-2.2.0@global
> /gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in
> require'
> /Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in
> block in require'
> /Users/asvechkar/.rvm/gems/ruby-2.2.0@global
> /gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in
> load_dependency'
> /Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in
> require'
> /Users/asvechkar/Projects/project/config.ru:3:inblock in
> '
> /Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/rack-1.6.0/lib/rack/builder.rb:55:in
> instance_eval'
> /Users/asvechkar/.rvm/gems/ruby-2.2.0@global
> /gems/rack-1.6.0/lib/rack/builder.rb:55:ininitialize'
> /Users/asvechkar/Projects/project/config.ru:in new'
> /Users/asvechkar/Projects/project/config.ru:in'
> /Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/rack-1.6.0/lib/rack/builder.rb:49:in
> eval'
> /Users/asvechkar/.rvm/gems/ruby-2.2.0@global
> /gems/rack-1.6.0/lib/rack/builder.rb:49:innew_from_string'
> /Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/rack-1.6.0/lib/rack/builder.rb:40:in
> parse_file'
> /Users/asvechkar/.rvm/gems/ruby-2.2.0@global
> /gems/rack-1.6.0/lib/rack/server.rb:299:in
> build_app_and_options_from_config'
> /Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/rack-1.6.0/lib/rack/server.rb:208:in
> app'
> /Users/asvechkar/.rvm/gems/ruby-2.2.0@global
> /gems/railties-4.2.0/lib/rails/commands/server.rb:61:inapp'
> /Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/rack-1.6.0/lib/rack/server.rb:336:in
> wrapped_app'
> /Users/asvechkar/.rvm/gems/ruby-2.2.0@global
> /gems/railties-4.2.0/lib/rails/commands/server.rb:139:inlog_to_stdout'
> /Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/commands/server.rb:78:in
> start'
> /Users/asvechkar/.rvm/gems/ruby-2.2.0@global
> /gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:80:inblock in
> server'
> /Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in
> tap'
> /Users/asvechkar/.rvm/gems/ruby-2.2.0@global
> /gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:inserver'
> /Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in
> run_command!'
> /Users/asvechkar/.rvm/gems/ruby-2.2.0@global
> /gems/railties-4.2.0/lib/rails/commands.rb:17:in'
> /Users/asvechkar/Projects/project/bin/rails:8:in require'
> /Users/asvechkar/Projects/project/bin/rails:8:in'
> /Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/ruby-debug-ide-0.4.28/bin/rdebug-ide:121:in
> `'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tryshoppe/shoppe/issues/182#issuecomment-97743980>.
>


-- 
Sent from Gmail Mobile

**Comment by asvechkar** [comment]
I solved this problem next solution:
In file environment.rb before Rails.application.initialize! insert:
I18n.load_path += Dir[Rails.root.join('config', 'locales', '*.{rb,yml}').to_s]

**Comment by deanperry** [comment]
And that's sorted it? Great, can you create a pull request and I'll merge
it?

On Thursday, April 30, 2015, Aleksey Svechkar <notifications@github.com>
wrote:

> I solved this problem next solution:
> In file environment.rb before Rails.application.initialize! insert:
> I18n.load_path += Dir[Rails.root.join('config', 'locales',
> '*.{rb,yml}').to_s]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tryshoppe/shoppe/issues/182#issuecomment-97746508>.
>


-- 
Sent from Gmail Mobile

**Comment by manzha** [comment]
Proposed solution also worked for me, thanks!. I put the code at the beginning of environment.rb (before load and initialize).

**Comment by andretanguy** [comment]
This has now been resolved on the shoppe-paypal gem: https://github.com/deanperry/shoppe-paypal/commit/c793ad83ec4212c6a9f1f79a2b19bf876dbb6720

**Comment by andretanguy** [comment]
@deanperry please close this issue :)

**Comment by deanperry** [comment]
This is now fixed in v1.1.1 of `shoppe-paypal` :+1:
