### ISSUE TITLE
@order.proceed_to_confirm

### ISSUE THREAD

**Issue by asvechkar** [tryshoppe/shoppe#183]
In page "Checkout" after fill order form I click on Continue.

Exec method:
```ruby
def checkout
    @order = Shoppe::Order.find(current_order.id)
    if request.patch?
      if @order.proceed_to_confirm(params[:order].permit(:first_name, :last_name,  :billing_country_id, :billing_postcode, :email_address, :phone_number))
        redirect_to checkout_payment_path
      end
    end
  end
```
@order.proceed_to_confirm return false, ActiveRecord rollback transaction on self.update.

What fields are required?

**Comment by deanperry** [comment]
I believe all the address details are required

**Comment by asvechkar** [comment]
But I don't need require this info from customers because I'll sell online goods. How to I fill required fields?

**Comment by asvechkar** [comment]
My form
.row
  .col-md-9
    = render 'items', :order => @order
  .col-md-3
    = form_for @order, :url => checkout_path do |f|
      .form-group
        = f.label :first_name, 'First name'
        = f.text_field :first_name, class: 'form-control', placeholder: 'First name'
      .form-group
        = f.label :first_name, 'Last name'
        = f.text_field :last_name, class: 'form-control', placeholder: 'Last name'
      .form-group
        = f.label :billing_postcode, 'Post code'
        = f.text_field :billing_postcode, class: 'form-control'
      .form-group
        = f.label :billing_country_id
        = f.collection_select :billing_country_id, Shoppe::Country.ordered, :id, :name, { prompt: 'Select country' }, { class: 'form-control' }
      .form-group
        = f.label :email_address
        = f.text_field :email_address, class: 'form-control', placeholder: 'your e-mail'
      .form-group
        = f.label :phone_number
        = f.phone_field :phone_number, class: 'form-control', placeholder: '8-123-456789'
      .form-group
        = f.hidden_field :billing_address1, value: '-'
        = f.hidden_field :billing_address2, value: '-'
        = f.hidden_field :billing_address3, value: '-'
        = f.hidden_field :billing_address4, value: '-'
        = f.submit 'Continue', class: 'btn btn-primary'

I fill all fields, but order don't proceed.

**Comment by deanperry** [comment]
It's hard to say without seeing the rest of the code. Have you followed the
tutorial on the Shoppe site?

On Thursday, May 7, 2015, Aleksey Svechkar <notifications@github.com> wrote:

> My form
> .row
> .col-md-9
> = render 'items', :order => @order <https://github.com/order>
> .col-md-3
> = form_for @order <https://github.com/order>, :url => checkout_path do |f|
> .form-group
> = f.label :first_name, 'First name'
> = f.text_field :first_name, class: 'form-control', placeholder: 'First
> name'
> .form-group
> = f.label :first_name, 'Last name'
> = f.text_field :last_name, class: 'form-control', placeholder: 'Last name'
> .form-group
> = f.label :billing_postcode, 'Post code'
> = f.text_field :billing_postcode, class: 'form-control'
> .form-group
> = f.label :billing_country_id
> = f.collection_select :billing_country_id, Shoppe::Country.ordered, :id,
> :name, { prompt: 'Select country' }, { class: 'form-control' }
> .form-group
> = f.label :email_address
> = f.text_field :email_address, class: 'form-control', placeholder: 'your
> e-mail'
> .form-group
> = f.label :phone_number
> = f.phone_field :phone_number, class: 'form-control', placeholder:
> '8-123-456789'
> .form-group
> = f.hidden_field :billing_address1, value: '-'
> = f.hidden_field :billing_address2, value: '-'
> = f.hidden_field :billing_address3, value: '-'
> = f.hidden_field :billing_address4, value: '-'
> = f.submit 'Continue', class: 'btn btn-primary'
>
> I fill all fields, but order don't proceed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tryshoppe/shoppe/issues/183#issuecomment-99884490>.
>


-- 
Sent from Gmail Mobile

**Comment by deanperry** [comment]
And what's the issue you're having? I assume the product has stock when
purchasing?

On Thursday, May 7, 2015, Aleksey Svechkar <notifications@github.com> wrote:

> My form
> .row
> .col-md-9
> = render 'items', :order => @order <https://github.com/order>
> .col-md-3
> = form_for @order <https://github.com/order>, :url => checkout_path do |f|
> .form-group
> = f.label :first_name, 'First name'
> = f.text_field :first_name, class: 'form-control', placeholder: 'First
> name'
> .form-group
> = f.label :first_name, 'Last name'
> = f.text_field :last_name, class: 'form-control', placeholder: 'Last name'
> .form-group
> = f.label :billing_postcode, 'Post code'
> = f.text_field :billing_postcode, class: 'form-control'
> .form-group
> = f.label :billing_country_id
> = f.collection_select :billing_country_id, Shoppe::Country.ordered, :id,
> :name, { prompt: 'Select country' }, { class: 'form-control' }
> .form-group
> = f.label :email_address
> = f.text_field :email_address, class: 'form-control', placeholder: 'your
> e-mail'
> .form-group
> = f.label :phone_number
> = f.phone_field :phone_number, class: 'form-control', placeholder:
> '8-123-456789'
> .form-group
> = f.hidden_field :billing_address1, value: '-'
> = f.hidden_field :billing_address2, value: '-'
> = f.hidden_field :billing_address3, value: '-'
> = f.hidden_field :billing_address4, value: '-'
> = f.submit 'Continue', class: 'btn btn-primary'
>
> I fill all fields, but order don't proceed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tryshoppe/shoppe/issues/183#issuecomment-99884490>.
>


-- 
Sent from Gmail Mobile

**Comment by asvechkar** [comment]
Yes, I follow tut.

**Comment by asvechkar** [comment]
fix it

**Comment by sammoore** [comment]
In case anyone else stumbles on this page, this drove me nuts for the longest time until I finally realized I needed to increase the stock levels of the product. I thought I followed the tutorial, but I probably missed something that went along these lines.

**Comment by mdarby** [comment]
.... and delivery service needs to be defined.
