### ISSUE TITLE
Link a product to multiple categories

### ISSUE THREAD

**Issue by andretanguy** [tryshoppe/shoppe#184]
Product needs the ability to belong to multiple categories. When creating a new product (or editing an existing one), simply use a "multiple" dropdown for the category.

**Comment by rubytree** [comment]
It hasn't been merged yet, but I'm using it in my project with no major issues: https://github.com/tryshoppe/shoppe/pull/137

**Comment by andretanguy** [comment]
Excellent, thanks @rubytree - ill take a look! Will mark this as closed due to duplication of #137
