### ISSUE TITLE
Reg:- Is it possible to attach multiple image to one product.

### ISSUE THREAD

**Issue by Ramesh-Palanivel** [tryshoppe/shoppe#185]
Is it possible to attach multiple image to one product.?
I want to add more then one image attach to a product..Let if it is possible?

Thanks

**Comment by rubytree** [comment]
You can merge this PR to your repo https://github.com/tryshoppe/shoppe/pull/169

**Comment by deanperry** [comment]
I haven't had time to finish off #169 but that should be the kind of thing you want

**Comment by andretanguy** [comment]
was thinking about this earlier! When do you think it'll be merged?

**Comment by deanperry** [comment]
I've got quite a bit on at the moment but I'll see if I can work on it this week

**Comment by Ramesh-Palanivel** [comment]
Ya i have installed gem 10days before.

**Comment by deanperry** [comment]
Attachments has now been merged into master - #169
