### ISSUE TITLE
rake shoppe:seed

### ISSUE THREAD

**Issue by asvechkar** [tryshoppe/shoppe#187]
I have Postgresql.

After rake db:migrate shoppe:setup I run rake shoppe:seed and see next error:
rake aborted!
ArgumentError: string contains null byte
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/oid/bytea.rb:8:in `unescape_bytea'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/oid/bytea.rb:8:in `type_cast_from_database'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/type/binary.rb:26:in `changed_in_place?'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/attribute.rb:54:in `changed_in_place_from?'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:74:in `attribute_changed_in_place?'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:149:in `block in changed_in_place'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:148:in `select'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:148:in `changed_in_place'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:141:in `attributes_changed_in_place'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:62:in `changed_attributes'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activemodel-4.2.0/lib/active_model/dirty.rb:173:in `attribute_changed?'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:107:in `save_changed_attribute'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:94:in `write_attribute'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/attribute_methods.rb:50:in `__temp__46164716'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/nifty-attachments-1.0.4/lib/nifty/attachments/attachment.rb:29:in `block in <class:Attachment>'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:441:in `instance_exec'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:163:in `call'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:163:in `block in halting'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `call'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_validation_callbacks'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activemodel-4.2.0/lib/active_model/validations/callbacks.rb:113:in `run_validations!'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activemodel-4.2.0/lib/active_model/validations.rb:334:in `valid?'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/validations.rb:58:in `valid?'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/validations.rb:83:in `perform_validations'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/validations.rb:37:in `save'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:21:in `save'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/transactions.rb:286:in `block (2 levels) in save'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/transactions.rb:347:in `block in with_transaction_returning_status'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/transactions.rb:220:in `transaction'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/transactions.rb:344:in `with_transaction_returning_status'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/transactions.rb:286:in `block in save'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/transactions.rb:285:in `save'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/associations/has_many_association.rb:40:in `insert_record'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/associations/collection_association.rb:491:in `block (2 levels) in _create_record'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/associations/collection_association.rb:398:in `replace_on_target'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/associations/collection_association.rb:393:in `add_to_target'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/associations/collection_association.rb:489:in `block in _create_record'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/associations/collection_association.rb:173:in `block in transaction'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/transactions.rb:220:in `transaction'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/associations/collection_association.rb:172:in `transaction'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/associations/collection_association.rb:488:in `_create_record'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/associations/has_many_association.rb:172:in `_create_record'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/associations/collection_association.rb:143:in `create'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/associations/collection_proxy.rb:285:in `create'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/nifty-attachments-1.0.4/lib/nifty/attachments/model_extension.rb:15:in `block (2 levels) in included'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/nifty-attachments-1.0.4/lib/nifty/attachments/model_extension.rb:13:in `each'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/nifty-attachments-1.0.4/lib/nifty/attachments/model_extension.rb:13:in `block in included'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:441:in `instance_exec'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:225:in `call'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:225:in `block in halting_and_conditional'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:219:in `call'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:219:in `block in halting_and_conditional'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:219:in `call'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:219:in `block in halting_and_conditional'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `call'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_save_callbacks'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/callbacks.rb:302:in `create_or_update'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/persistence.rb:142:in `save!'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/validations.rb:43:in `save!'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/transactions.rb:291:in `block in save!'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/transactions.rb:347:in `block in with_transaction_returning_status'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/transactions.rb:220:in `transaction'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/transactions.rb:344:in `with_transaction_returning_status'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/transactions.rb:291:in `save!'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/shoppe-1.0.5/db/seeds.rb:35:in `<top (required)>'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/shoppe-1.0.5/lib/tasks/shoppe.rake:4:in `block (2 levels) in <top (required)>'
Tasks: TOP => shoppe:seed
(See full trace by running task with --trace)

**Comment by deanperry** [comment]
Hey, this is a bug in Rails. Updating to 4.2.1 should fix it :)

On Thursday, May 7, 2015, Aleksey Svechkar <notifications@github.com> wrote:

> I have Postgresql.
>
> After rake db:migrate shoppe:setup I run rake shoppe:seed and see next
> error:
> rake aborted!
> ArgumentError: string contains null byte
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/oid/bytea.rb:8:in
> unescape_bytea'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/oid/bytea.rb:8:in
> type_cast_from_database'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/type/binary.rb:26:in
> changed_in_place?'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/attribute.rb:54:in
> changed_in_place_from?'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:74:in
> attribute_changed_in_place?'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:149:inblock
> in changed_in_place'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:148:in
> select'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:148:in
> changed_in_place'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:141:in
> attributes_changed_in_place'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:62:in
> changed_attributes'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activemodel-4.2.0/lib/active_model/dirty.rb:173:in
> attribute_changed?'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:107:in
> save_changed_attribute'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:94:in
> write_attribute'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/attribute_methods.rb:50:in
> __temp__46164716'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/nifty-attachments-1.0.4/lib/nifty/attachments/attachment.rb:29:in
> block in <class:Attachment>'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:441:in
> instance_exec'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:441:in
> block in make_lambda'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:163:in
> call'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:163:in
> block in halting'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in
> call'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in
> block in halting'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in
> call'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in
> _run_callbacks'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in
> _run_validation_callbacks'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activemodel-4.2.0/lib/active_model/validations/callbacks.rb:113:in
> run_validations!'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activemodel-4.2.0/lib/active_model/validations.rb:334:in
> valid?'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/validations.rb:58:in
> valid?'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/validations.rb:83:in
> perform_validations'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/validations.rb:37:in
> save'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:21:in
> save'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/transactions.rb:286:in
> block (2 levels) in save'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/transactions.rb:347:inblock
> in with_transaction_returning_status'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in
> transaction'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/transactions.rb:220:in
> transaction'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/transactions.rb:344:in
> with_transaction_returning_status'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/transactions.rb:286:inblock
> in save'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/transactions.rb:301:in
> rollback_active_record_state!'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/transactions.rb:285:in
> save'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/associations/has_many_association.rb:40:in
> insert_record'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/associations/collection_association.rb:491:inblock
> (2 levels) in _create_record'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/associations/collection_association.rb:398:in
> replace_on_target'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/associations/collection_association.rb:393:in
> add_to_target'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/associations/collection_association.rb:489:in
> block in _create_record'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/associations/collection_association.rb:173:inblock
> in transaction'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in
> transaction'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/transactions.rb:220:in
> transaction'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/associations/collection_association.rb:172:in
> transaction'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/associations/collection_association.rb:488:in
> _create_record'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/associations/has_many_association.rb:172:in
> _create_record'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/associations/collection_association.rb:143:in
> create'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/associations/collection_proxy.rb:285:in
> create'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/nifty-attachments-1.0.4/lib/nifty/attachments/model_extension.rb:15:inblock
> (2 levels) in included'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/nifty-attachments-1.0.4/lib/nifty/attachments/model_extension.rb:13:in
> each'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/nifty-attachments-1.0.4/lib/nifty/attachments/model_extension.rb:13:inblock
> in included'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:441:in
> instance_exec'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:441:inblock
> in make_lambda'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:225:in
> call'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:225:inblock
> in halting_and_conditional'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:219:in
> call'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:219:inblock
> in halting_and_conditional'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:219:in
> call'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:219:inblock
> in halting_and_conditional'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in
> call'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in
> _run_callbacks'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in
> _run_save_callbacks'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/callbacks.rb:302:in
> create_or_update'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/persistence.rb:142:in
> save!'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/validations.rb:43:in
> save!'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:29:in
> save!'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/transactions.rb:291:inblock
> in save!'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/transactions.rb:347:in
> block in with_transaction_returning_status'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:inblock
> in transaction'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:188:in
> within_new_transaction'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in
> transaction'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/transactions.rb:220:in
> transaction'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/transactions.rb:344:in
> with_transaction_returning_status'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/transactions.rb:291:in
> save!'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/shoppe-1.0.5/db/seeds.rb:35:in'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in
> require'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:inblock
> in require'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in
> load_dependency'
>
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in
> require'
> /Users/asvechkar/.rvm/gems/ruby-2.2.1/gems/shoppe-1.0.5/lib/tasks/shoppe.rake:4:in
> `block (2 levels) in '
> Tasks: TOP => shoppe:seed
> (See full trace by running task with --trace)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tryshoppe/shoppe/issues/187>.
>


-- 
Sent from Gmail Mobile

**Comment by asvechkar** [comment]
Thanks for advice ;)

**Comment by kumar91gopi** [comment]
i am facing the same issue. i upgraded my Rails version to 4.2.1 and Ruby 2.2.1 but still the rake is aborted.
----------------------------
kumar91gopi@shoppe:~/workspace/wardrobe $ rake shoppe:seed
rake aborted!
NoMethodError: undefined method `default_image_file=' for #<Shoppe::Product:0x000000076a2988>
/usr/local/rvm/gems/ruby-2.2.1/gems/activemodel-4.2.1/lib/active_model/attribute_methods.rb:433:in `method_missing'
/usr/local/rvm/gems/ruby-2.2.1/gems/shoppe-1.1.0/db/seeds.rb:35:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.2.1/gems/shoppe-1.1.0/lib/tasks/shoppe.rake:5:in `block (2 levels) in <top (required)>'
Tasks: TOP => shoppe:seed
(See full trace by running task with --trace)

**Comment by kimngoctran** [comment]
i have the same issue too.

**Comment by deanperry** [comment]
Hmm I'll see if I can take a look over the weekend
