### ISSUE TITLE
redirect to payment form

### ISSUE THREAD

**Issue by 5sp4lr** [tryshoppe/shoppe#191]
So after the required fields in the checkout form are filled, the payment page/form isnt loaded.

my controller

```
def checkout
  @order = Shoppe::Order.find(current_order.id)
  if request.patch?
    if @order.proceed_to_confirm(params[:order].permit(:first_name, :last_name, :billing_address2, :email_address, :phone_number))
      redirect_to checkout_payment_path
    end
  end
end
```

and i have the routes set from following the documentation on the website

**Comment by andretanguy** [comment]
Try this:

def checkout
    @order = Shoppe::Order.find(current_order.id)
    if request.patch?
      @order.attributes = params[:order].permit(:first_name, :last_name, :company, :billing_address1, :billing_address2, :billing_address3, :billing_address4, :billing_country_id, :billing_postcode, :email_address, :phone_number, :delivery_name, :delivery_address1, :delivery_address2, :delivery_address3, :delivery_address4, :delivery_postcode, :delivery_country_id, :separate_delivery_address)
      @order.ip_address = request.ip
      if @order.proceed_to_confirm
        redirect_to checkout_payment_path
      end
    end
  end

**Comment by 5sp4lr** [comment]
@andretanguy  still nothing.

**Comment by andretanguy** [comment]
Can you paste your entire orders_controller.rb to paste.codebasehq.com

**Comment by 5sp4lr** [comment]
http://paste.codebasehq.com/pastes/j5dge941pyp0i88i8x

**Comment by deanperry** [comment]
I believe you need all address fields filled out as they are all required

**Comment by andretanguy** [comment]
Your controller looks like it's missing a few key methods. Have you taken a look at the example store? FYI, here's an orders_controller.rb that is setup to work with the shoppe-stripe gem for card payments: http://paste.codebasehq.com/pastes/nxhcegacq063ai3ln0

**Comment by andretanguy** [comment]
Here's where the example-store code can be found: https://github.com/tryshoppe/shoppe-example/blob/master/app/controllers/orders_controller.rb

**Comment by 5sp4lr** [comment]
@deanperry i tried it with all address fields and the problem stil persists. I only need one address field for the project i am working on so i removed that the others should be required

@andretanguy  I am using the example store as reference already. I am so confused right now lol because i am following this : http://tryshoppe.com/docs/tutorials/checking-out

**Comment by 5sp4lr** [comment]
should i upload my entire repository?

**Comment by 5sp4lr** [comment]
@ Deanperry

Ok so in my checkout form i only have 5 fields. This is due to the fact that i am making a small e commerce website. For a specific island. All i need are FName, LName, Address 1, email, phone number. apparently for the checkout process to work i need every single feild ie address 1 -4, country,post code etc. Please tell me there is a workaround to this.

**Comment by 5sp4lr** [comment]
also the checkout method here http://paste.codebasehq.com/pastes/kxsbdebmbyfd8vmi1x
allows for Fakers, which i assume is the preloaded data on the example website. This doesnt work for me. But i would love to know how to do this for a clean work around to my problem

**Comment by 5sp4lr** [comment]
well since i have no time i decided to just work around the problem. Hopefully my instructors dont figure out what i did xD. I just auto filled the required fields with faker and hid them with css. I will close this. Thanks
