### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by 5sp4lr** [tryshoppe/shoppe#192]
Is there a way to add such a thing to a shoppe app?

**Comment by andretanguy** [comment]
Already exists as 'filters' - you'll need to implement your own UI for this though

**Comment by deanperry** [comment]
In the shoppe admin or to your rails app? See here if you want to add it to the front end. Personally I'm using Ransack in most of my apps these days but you can use a simple search. Depends on what you want to search for really and how complex you want the search http://railscasts.com/?tag_id=30





On Fri, May 15, 2015 at 10:17 PM -0700, "5sp4lr" <notifications@github.com> wrote:












Is there a way to add such a thing to a shoppe app?

**Comment by 5sp4lr** [comment]
@deanperry thanks so much. @andretanguy, about this filters thing, can i get some more info on this, please? i dont quite understand.

Also sorry for all the questions guys, this is gonna be a busy coding weekend lol

**Comment by deanperry** [comment]
Shoppe uses Ransack on the back end which is a very powerful gem so you can use this - https://github.com/activerecord-hackery/ransack
