### ISSUE TITLE
rake shoppe:seed throws error

### ISSUE THREAD

**Issue by mohsalsaleem** [tryshoppe/shoppe#193]
I followed the docs to setup rails but it shows error

rails version: 4.2.1
ruby version: ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]

the error showed is : 

$ rake shoppe:seed
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: must add at least one product category
/home/saleem/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/validations.rb:79:in `raise_record_invalid'
/home/saleem/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/validations.rb:43:in `save!'
/home/saleem/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/home/saleem/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/transactions.rb:291:in `block in save!'
/home/saleem/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/transactions.rb:347:in `block in with_transaction_returning_status'
/home/saleem/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
/home/saleem/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/transactions.rb:220:in `transaction'
/home/saleem/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/transactions.rb:344:in `with_transaction_returning_status'
/home/saleem/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/transactions.rb:291:in `save!'
/home/saleem/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/associations/has_many_through_association.rb:60:in `insert_record'
/home/saleem/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/associations/collection_association.rb:501:in `block (2 levels) in _create_record'
/home/saleem/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/associations/collection_association.rb:408:in `replace_on_target'
/home/saleem/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/associations/collection_association.rb:403:in `add_to_target'
/home/saleem/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/associations/collection_association.rb:499:in `block in _create_record'
/home/saleem/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/associations/collection_association.rb:183:in `block in transaction'
/home/saleem/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/home/saleem/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/home/saleem/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/home/saleem/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/transactions.rb:220:in `transaction'
/home/saleem/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/associations/collection_association.rb:182:in `transaction'
/home/saleem/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/associations/collection_association.rb:498:in `_create_record'
/home/saleem/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/associations/has_many_association.rb:180:in `_create_record'
/home/saleem/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/associations/collection_association.rb:157:in `create!'
/home/saleem/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/associations/collection_proxy.rb:306:in `create!'
/home/saleem/.rvm/gems/ruby-2.2.2/gems/shoppe-1.0.6/db/seeds.rb:33:in `<top (required)>'
/home/saleem/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/home/saleem/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
/home/saleem/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/saleem/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/home/saleem/.rvm/gems/ruby-2.2.2/gems/shoppe-1.0.6/lib/tasks/shoppe.rake:4:in `block (2 levels) in <top (required)>'
/home/saleem/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
/home/saleem/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
/home/saleem/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/saleem/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
-e:1:in `<main>'
Tasks: TOP => shoppe:seed
(See full trace by running task with --trace)

**Comment by deanperry** [comment]
This is now fixed in v1.0.7 :+1:
