### ISSUE TITLE
Custom Fees?

### ISSUE THREAD

**Issue by danielricecodes** [tryshoppe/shoppe#197]
Hello, I'm evaluating Shoppe as a potential backend replacement for an existing Rails based E-commerce system.  Is it possible to use a Tax or Fee Calculator class instead of the provided taxation interface?  The app I support doesn't need to calculate Tax, but it does need to calculate a variable transaction fee that is based on the order total.  

Thanks in advance.

**Comment by deanperry** [comment]
Yep, you are better off forking the gem to make those changes as that is out of the scope of shoppe

**Comment by danielricecodes** [comment]
Ok thank you

--
Daniel Rice
==================
