### ISSUE TITLE
Association named 'product_category' was not found on Shoppe::Product

### ISSUE THREAD

**Issue by alexdaish** [tryshoppe/shoppe#201]
Followed the instructions from here (http://tryshoppe.com/docs/tutorials/products) twice (second time copying and pasting to eliminate errors) but I get this message. I've restarted the server twice but I can't see what I've done wrong.

![screen shot 2015-05-21 at 16 41 41](https://cloud.githubusercontent.com/assets/7382128/7752764/4aa4403e-ffd9-11e4-9c52-19c2b8bd3787.png)

The first time I also put Shoppe into demo mode but could never disable it again as you couldn't change settings once in demo mode.

Really like what your doing though. I think my Mum might actually be able to manage the back end.

**Comment by deanperry** [comment]
Ah this may be due to the change with product categories. I'll see if I can update the tutorial over the weekend

**Comment by alexdaish** [comment]
That would be fantastic. Thanks very much. Once you've done that I'll keep going and holler if I find any more bugs. :+1:

**Comment by paplm** [comment]
got same problem, edit line#4 in products_controller.rb to be
```ruby
    @products = Shoppe::Product.root.ordered.includes(:product_categories, :variants)
```
is works for me

**Comment by alexdaish** [comment]
@paplm Thank's I'll try this.

**Comment by alexdaish** [comment]
Yep this works! :+1:
