### ISSUE TITLE
Association named 'product_category' was not found on Shoppe::Product; perhaps you misspelled it?

### ISSUE THREAD

**Issue by dileepkushwaha** [tryshoppe/shoppe#203]
Hi i am new to ruby and to shoppe gem. I was following the doc http://tryshoppe.com/docs/tutorials/products
while adding the controller product and starting the rail server i am getting the following errors:
ActiveRecord::AssociationNotFoundError in ProductsController#index
Association named 'product_category' was not found on Shoppe::Product; perhaps you misspelled it?

Extracted source (around line #5):
3
4
5
6
7
8
              
  def index
    @products = Shoppe::Product.root.ordered.includes(:product_category, :variants)
    @products = @products.group_by(&:product_category)
  end

  def show

Rails.root: /home/dp/ruby_project/eshop

Application Trace | Framework Trace | Full Trace
app/controllers/products_controller.rb:5:in `index'

![image](https://cloud.githubusercontent.com/assets/3797167/7924626/852822de-08da-11e5-924e-13a75de09f33.png)

**Comment by andretanguy** [comment]
see issue #204 and https://github.com/farukaydin/documentation/commit/cf8e0bab7067b493f55abf732f03a235460c722c - product_category has become product_categories

**Comment by deanperry** [comment]
Apologies for the delay. I've updated the documentation - http://tryshoppe.com/docs/tutorials/products. See product_category -> product_categories
