### ISSUE TITLE
Association named 'product_category' was not found on Shoppe::Product

### ISSUE THREAD

**Issue by son1112** [tryshoppe/shoppe#204]
Following the Getting Started Series (http://tryshoppe.com/docs/tutorials/getting-started), after modifying the products controller:

    def index
        @products = Shoppe::Product.root.ordered.includes(:product_category, :variants)
        @products = @products.group_by(&:product_category)
    end

    def show
        @product = Shoppe::Product.find_by_permalink(params[:permalink])
    end

And adding routes (not sure if order is important here, but I have tried both with "mount Shoppe..." before and after other routing commands):

    get "product/:permalink", to: "products#show", as: "product"
    post "product/:permalink", to: "products#buy", as: "buy"
    root to: "products#index"

    mount Shoppe::Engine => "/shoppe"

After creating an index page, making sure all of Shoppe's migrations and setup have been completed according to the guide, and restarting the server, I consistently receive the following error when attempting to load the index page for the projects controller (ie. /shoppe still loads the shoppe admin AND the seeded data for product categories is present):

    Started GET "/" for ::1 at 2015-06-03 10:49:26 +0000
    Processing by ProductsController#index as HTML
        ESC[1mESC[35mShoppe::Product Load (1.6ms)ESC[0m  SELECT "shoppe_products".* FROM "shoppe_products" WHERE "shoppe_products"."parent_id" IS NULL  ORDER
       BY "shoppe_products"."default" DESC, "shoppe_products"."name" ASC
    Completed 500 Internal Server Error in 13ms (ActiveRecord: 1.6ms)

    ActiveRecord::AssociationNotFoundError (Association named 'product_category' was not found on Shoppe::Product; perhaps you misspelled it?):
        app/controllers/products_controller.rb:5:in `index'

I checked *schema.rb* for references to product categories for clues. Perhaps the names in documentation have not been updated to a naming change in the migration:

    create_table "shoppe_product_categories", force: :cascade do |t|
        t.string   "name"
        t.string   "permalink"
        t.text     "description"
        t.datetime "created_at"
        t.datetime "updated_at"
        t.integer  "parent_id"
        t.integer  "lft"
        t.integer  "rgt"
        t.integer  "depth"
        t.string   "ancestral_permalink"
        t.boolean  "permalink_includes_ancestors", default: false
    end

    add_index "shoppe_product_categories", ["lft"], name: "index_shoppe_product_categories_on_lft"
    add_index "shoppe_product_categories", ["permalink"], name: "index_shoppe_product_categories_on_permalink"
    add_index "shoppe_product_categories", ["rgt"], name: "index_shoppe_product_categories_on_rgt"

    create_table "shoppe_product_categorizations", force: :cascade do |t|
        t.integer "product_id",          null: false
        t.integer "product_category_id", null: false
    end

    add_index "shoppe_product_categorizations", ["product_category_id"], name: "categorization_by_product_category_id"
    add_index "shoppe_product_categorizations", ["product_id"], name: "categorization_by_product_id"

Any suggestions?

Thank you

**Comment by deanperry** [comment]
This is fixed in documentation#8. I'll push the update shortly

**Comment by son1112** [comment]
awesome. thank you

**Comment by andretanguy** [comment]
index is fixed, but not show - the current method delivers an exception for the show action.

**Comment by deanperry** [comment]
Apologies for the delay. I've updated the documentation - http://tryshoppe.com/docs/tutorials/products. See product_category -> product_categories
