### ISSUE TITLE
Docu "Working with Shoppe baskets"

### ISSUE THREAD

**Issue by erikpaperik** [tryshoppe/shoppe#206]
This [guide](http://tryshoppe.com/docs/tutorials/baskets) explains that the relationship between customer and order for implementing a basket should be established by using the ```ip_address```.

That means that two customers behind a proxy would share the same basket right?!

Maybe it's better to use a unique session id for this purpose.

**Comment by deanperry** [comment]
Nope, I believe it's stored as a session for that user. I'll take a look though.

**Comment by erikpaperik** [comment]
You are right. The ```:order_id``` is stored in the users session (```session[:order_id] = order.id```).

Imagine the following scenario:
* Person A and person B are behind the same proxy
* Person A visits the shop and adds an item to the basket -> This action creates an order with ```ip_address``` as reference to customer and stores ```:order_id``` in the users session
* Person B visits the shop and gets the basket of person A, because the share the same ip address
