### ISSUE TITLE
Default admin account in production (heroku)

### ISSUE THREAD

**Issue by chbrown1293** [tryshoppe/shoppe#207]
Hey there! Seriously love this solution - mad props!! 

I am just having some trouble logging in as an admin when my app is pushed to heroku. I was looking through your seeds and couldnt find anything about a Shoppe::User, how is the initial user created in development? Should I be writing some seed data to create one in production?

Thanks a lot! 
Chris

**Comment by chbrown1293** [comment]
Nevermind I'm a total noob!! 

For anyone wondering, I had to run "heroku run rake shoppe:setup", then "heroku run rake shoppe:seed". 

Seems to be working absolutely wonderfully. Again, you guys kicked ass on this puppy. Cant even tell you how stoked I am on it :).

**Comment by tzurcan** [comment]
Thanks, man helped me, too

**Comment by tzurcan** [comment]
do not run heroku run rake shoppe:seed if You do not need the default items, as it takes longer to edit/remove them from the app
