### ISSUE TITLE
NoMethodError in Shoppe::Settings#edit

### ISSUE THREAD

**Issue by Debsideb** [tryshoppe/shoppe#217]
Can't access the settings of my back-office dashboard it raises the error mentioned above.
Line 12: %dt= settings_label f

**Comment by deanperry** [comment]
This is the same as #214 but I can't replicate it on a new Rails 4.2.3 app. What other gems do you have and what version of Shoppe?

**Comment by Debsideb** [comment]
Yes it worked. Only had to update to rails 4.2.3 as you mentioned in #214 ;)

**Comment by deanperry** [comment]
Great :)

**Comment by tzurcan** [comment]
helped me , as well, had to downgrade from 4.2.6
