### ISSUE TITLE
NoMethodError in Products#show

### ISSUE THREAD

**Issue by Debsideb** [tryshoppe/shoppe#218]
I'm a newbie in rails and I just updated to the latest version of Shoppe(1.0.8) but nothing works anymore unfortunately. Did I miss something?

**Comment by deanperry** [comment]
It depends on the error. You'll need to run the latest migrations `rake db:migrate` and also update your controllers for the new product categories as per this tutorial - http://tryshoppe.com/docs/tutorials/products

**Comment by Debsideb** [comment]
Okay yes it was the migration missing but it raises a no method error in product#show. 
<h2><%= @product.name %></h2>

**Comment by deanperry** [comment]
Hmm this should be working. I'll test it again on a working app I've got

**Comment by deanperry** [comment]
I can't seem to replicate this issue, can you list your Gemfile?

**Comment by Debsideb** [comment]
sure: here it is :)

gem 'rails', '4.2.3'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
# gem 'therubyracer', platforms: :ruby
gem 'shoppe'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'bootstrap-sass', '~> 3.3.1'
gem 'font-awesome-sass', '~> 4.2.0'
gem 'simple_form'

# gem 'bcrypt', '~> 3.1.7'

# gem 'unicorn'

# gem 'capistrano-rails', group: :development

group :development, :test do

  gem 'byebug'

  gem 'web-console', '~> 2.0'
  gem 'spring'

**Comment by deanperry** [comment]
I still can't replicate it. What if you copy some of the code from the example app?  https://github.com/tryshoppe/shoppe-example

**Comment by Debsideb** [comment]
Okay I'll try that ;)

**Comment by Debsideb** [comment]
I tried to re-install shoppe from scratch and do a new application to see where was the bug. I followed the tutorial but it still gives the error as shown below
![screen shot 2015-06-28 at 12 25 37](https://cloud.githubusercontent.com/assets/12230858/8395972/da812756-1d90-11e5-93bb-dc60088e528e.png)

**Comment by deanperry** [comment]
Hmm ok I'll see if I can take a look later today

**Comment by sammoore** [comment]
What does your ProductsController look like, assuming that's the controller with this view?

**Comment by tsimehcppa** [comment]
i used "rails console --sandbox" and typing the following:
Shoppe::Product.find_by_permalink('snom-870')

and the response is :
--------------------------------------------------------
 SELECT  "shoppe_products".* FROM "shoppe_products" INNER JOIN "shoppe_product_translations" ON "shoppe_product_translations"."shoppe_product_id" = "shoppe_products"."id" WHERE "shoppe_product_translations"."permalink" = '--- !ruby/object:ActiveRecord::StatementCache::Substitute {}
' AND "shoppe_product_translations"."locale" = ? LIMIT 1  [["locale", "en"]]
=> nil
--------------------------------------------------------
So the @product is nil and <%= @product.name %> return no method

**Comment by Debsideb** [comment]
@sammoore : This is my ProductsController that comes from the tutorial. 
![screen shot 2015-06-29 at 09 31 37](https://cloud.githubusercontent.com/assets/12230858/8403098/d2724c5a-1e41-11e5-9e95-5eb210fbe7ea.png)

**Comment by renyuanz** [comment]
I had the same issue by following the tutorial.

@tsimehcppa reminds me to check out sandbox.
This is my solution:
There is something missing in 'buy' and 'show' action:
**Just change :**
Shoppe::Product.find_by_*
**to**
Shoppe::Product.root.find_by_*
![solu](https://cloud.githubusercontent.com/assets/10615036/8409044/06659dae-1e75-11e5-9577-17d326a0fd97.jpg)

@Debsideb hope this could help.

**Comment by Debsideb** [comment]
@renyuanz thanks man, it helped a lot! Everything works again :)

**Comment by deanperry** [comment]
Excellent, I'll update the documentation tonight

**Comment by renyuanz** [comment]
@Debsideb you are welcome :P

**Comment by deanperry** [comment]
I've updated the docs. Thanks! :+1:
