### ISSUE TITLE
rake task to migrate nifty_attachments to shoppe_attachments

### ISSUE THREAD

**Issue by andretanguy** [tryshoppe/shoppe#219]
After merging #211 we need to ensure that there is a way to migrate previously uploaded images using nifty_attachments to carrierwave. A either a rake task or migration would be the best resolution.

**Comment by deanperry** [comment]
Good idea, I'll create a rake task :+1:

**Comment by deanperry** [comment]
You can run this. I've just tested it on a local copy of your shop :)

```ruby
attachments = Nifty::Attachments::Attachment.all

attachments.each do |attachment|
  object = attachment.parent_type.constantize.find(attachment.parent_id)

  attach = object.attachments.build
  attach.role = attachment.role
  attach.file_name = attachment.file_name

  tempfile = Tempfile.new("attach-#{attachment.token}")
  tempfile.binmode
  tempfile.write(attachment.data)
  uploaded_file = ActionDispatch::Http::UploadedFile.new(tempfile: tempfile, filename: attachment.file_name, type: attachment.file_type)

  attach.file = uploaded_file
  attach.save!

end
```

**Comment by deanperry** [comment]
You'll need to add the `nifty-attachments` gem to your Gemfile as this has been removed as a dependency

**Comment by deanperry** [comment]
I've added the documentation, I'll push the latest version tonight or by the weekend - http://tryshoppe.com/docs/attachments

**Comment by deanperry** [comment]
OK v1.0.9 is released :)

**Comment by jasmo2** [comment]
Hello , 
I am trying to serve static images with nifty:attachments
But it seems that the route does not exist.
What could be hapenning. Also I'm feeding the images with the seed. I am going to try manually and i let you know
