### ISSUE TITLE
item with size and color variants

### ISSUE THREAD

**Issue by ikhakoo** [tryshoppe/shoppe#220]
Hi - I am using the shoppe gem to build a clothing store and one of the things we have is multiple sizes for items.  What would be the best way to nest these and have them post to order form when the user does "add to cart"

I am a little new to rails so any help would be great.

Thanks in advance.

**Comment by deanperry** [comment]
You can create different variants for products, does that help?

**Comment by ikhakoo** [comment]
I was hoping there would be a way for me to do that without having so many products since i don't care much about stock control and mainly care about attributes like color and sizes.  I'll play around with it a bit but I think I was hoping for a variant of a variant in someways as in my scenario I have Item -> Colors -> Sizes type of relationship. I'll have to come up with some work around but I should be able to figure something out :)
