### ISSUE TITLE
Product Attributes Section

### ISSUE THREAD

**Issue by son1112** [tryshoppe/shoppe#221]
In the Admin/Product edit/create section, there is a field for adding an "Attribute" to the product, however I do not see the new attribute within the console and am unsure how to reference the new attribute. Am I misunderstanding the purpose of the ability to add a new attribute to a product from the admin settings?

**Comment by deanperry** [comment]
I think you can just run `@product.attributes`

**Comment by son1112** [comment]
@product.attributes does return a hash of the product's attributes, however, the attribute created within the Product admin does not appear in this set of attributes.

**Comment by deanperry** [comment]
Ah it's actually `@product.product_attributes`

**Comment by son1112** [comment]
Thanks!
