### ISSUE TITLE
How does a user can choose the day he wants to be delivered?

### ISSUE THREAD

**Issue by Debsideb** [tryshoppe/shoppe#222]
Not sure if you guys already figured it out in other questions, but it would be nice if the user can choose a delivery day and not have it by default.

**Comment by andretanguy** [comment]
This is outside the scope of Shoppe. There are delivery methods that can be set, but if you want to enable defined delivery days, that would need to be custom built for your store.

**Comment by deanperry** [comment]
Yep, Shoppe was made to be simple so I'll close this issue.
