### ISSUE TITLE
Can't proceed to payment page anymore :s

### ISSUE THREAD

**Issue by Debsideb** [tryshoppe/shoppe#223]
When a user fills in his informations (I've hidden and given a value to two address fields) the payment page doesn't load anymore. Even if I unhide the fields, it doesn't work :s.

My controller: 

def checkout
    @order = Shoppe::Order.find(current_order.id)
    if request.patch?
      if @order.proceed_to_confirm(params[:order].permit(:first_name, :last_name, :billing_address1, :billing_address2, :billing_address3, :billing_address4, :billing_country_id, :billing_postcode, :email_address, :phone_number))
      redirect_to checkout_payment_path
      end
    end
  end

**Comment by Debsideb** [comment]
Okay found a way around it. I'll close this now ;)

**Comment by son1112** [comment]
@Debsideb would you mind sharing with me how you worked around it? I'm currently struggling with this.

**Comment by deanperry** [comment]
All the address fields need to be filled out

**Comment by Debsideb** [comment]
Hey @son1112, you actually have to hide the address fields in the view and give them a value. The code for this looks like this: 

 <%= f.hidden_field :billing_address2, value: "test" %>

It works great for me.

**Comment by son1112** [comment]
hmmm. only for those that i don't need input for, right? are there other fields that need the same?

**Comment by Debsideb** [comment]
Yes actually you can use this trick only for the things that you don't need the user input for. Since Shoppe is requiring these fields to be filled, what you do is you pre-fill them by giving them a value ("test" in this case) and of course you don't want your user to see all those "test" in the fields so you hide them. You can hide them all if you don't need any address but what I did is to let the first one visible and free for user input and hid the other ones.

**Comment by son1112** [comment]
This is not working for me, unless there are other fields that are missing. I am needing 3 of the billing address fields, hiding the 4th. Do we have a list of all of the Shoppe-required fields that would need to be given a hidden "test" value? Are delivery services values required as well?

**Comment by deanperry** [comment]
I believe so yes but you can create one as free






On Tue, Jul 14, 2015 at 6:38 AM -0700, "Anderson Reinkordt" <notifications@github.com> wrote:












This is not working for me, unless there are other fields that are missing. I am needing 3 of the billing address fields, hiding the 4th. Do we have a list of all of the Shoppe-required fields that would need to be given a hidden "test" value? Are delivery services values required as well?

**Comment by son1112** [comment]
Okay, that seemed to be the issue. Thanks!
