### ISSUE TITLE
Tutorials Error::UnorderableItem for items have variants

### ISSUE THREAD

**Issue by renyuanz** [tryshoppe/shoppe#224]
I had a trouble shooting few days ago. As I followed the tutorials to create a basket and I used the seeded data, I can not add **"Snom 870"** this item to basket. It raised a `Shoppe::Errors::UnorderableItem`. So I traced back to source code and I found this:

```ruby
def orderable?
  return false unless self.active?
  return false if self.has_variants?
  true
end
```
And, this item "Snom 870" does have variants. So I deleted his variants and retried to "buy" it, finally it worked.

I think this would help people have the same problem and improve the tutorial maybe :)

**Comment by deanperry** [comment]
That error normally happens if the item doesn't have any stock

**Comment by renyuanz** [comment]
I'll add his variants back and test.

**Comment by renyuanz** [comment]
@deanperry it seems that problem is still there. And all his variants have stock.
I think it because we did nothing to handle items that have variants. 
So when it comes to call this method and it detects this item has variants, it returns false, and then raise an error `UnorderableItem`
```ruby
def has_variants?
  !variants.empty?
end
```

I don't know if i was right, but when I deleted his variants, it works again.

**Comment by renyuanz** [comment]
And I do alse have an error raised when I try to create a new variant for a product.
`ActionController::UrlGenerationError in Shoppe::Variants#new`

Showing /Users/renyuan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/shoppe-1.0.8/app/views/shoppe/variants/form.html.haml where line #4 raised:

No route matches {:action=>"index", :controller=>"shoppe/product_localisations", :product_id=>#<Shoppe::Product id: nil, parent_id: 1, name: nil, sku: nil, permalink: nil, description: nil, short_description: nil, active: true, weight: #<BigDecimal:7faa3335a658,'0.0',9(18)>, price: #<BigDecimal:7faa3335a4a0,'0.0',9(18)>, cost_price: #<BigDecimal:7faa3335a2e8,'0.0',9(18)>, tax_rate_id: nil, created_at: nil, updated_at: nil, featured: false, in_the_box: nil, stock_control: true, default: false>} missing required keys: [:product_id]

but I can see `product_id` received in params:

Request
Parameters:
{"product_id"=>"1"}

**Comment by deanperry** [comment]
What if you use the latest version of Shoppe?

**Comment by renyuanz** [comment]
@deanperry this error still there even if I updated to shoppe 1.0.9

ActionController::UrlGenerationError in Shoppe::Variants#new

Showing /Users/renyuan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/shoppe-1.0.9/app/views/shoppe/variants/form.html.haml where line #4 raised:

No route matches {:action=>"index", :controller=>"shoppe/product_localisations", :product_id=>#<Shoppe::Product id: nil, parent_id: 8, name: nil, sku: nil, permalink: nil, description: nil, short_description: nil, active: true, weight: #<BigDecimal:7fc90ac8dc98,'0.0',9(18)>, price: #<BigDecimal:7fc90ac8d900,'0.0',9(18)>, cost_price: #<BigDecimal:7fc90ac8d590,'0.0',9(18)>, tax_rate_id: nil, created_at: nil, updated_at: nil, featured: false, in_the_box: nil, stock_control: true, default: false>} missing required keys: [:product_id]

**Comment by renyuanz** [comment]
Apparently, 1.0.9 is not stable, I tried to update demo store to 1.0.9 but I got many errors, like I can not access to products#show and products variants. But everything went good if I switched back to 1.0.7. 
I can only figure out there is something wrong in 1.0.9's shoppe engines views.
