### ISSUE TITLE
rails generate nifty:attachments:migration - Could not find generator 'nifty:attachments:migration'.

### ISSUE THREAD

**Issue by estelleccl** [tryshoppe/shoppe#225]
Hi All,

Im using rails 4.2.1.

When I follow the documentation, to run  ``` rails generate nifty:attachments:migration```

I got the following error:
``` Could not find generator 'nifty:attachments:migration'. Maybe you meant 'nifty:key_value_store:migration' or 'active_record:migration' or 'test_unit:integration'
Run `rails generate --help` for more options. ```

Help!

**Comment by deanperry** [comment]
If you're using the latest version of Shoppe you don't need to run that
command. I'll update the docs for that

**Comment by estelleccl** [comment]
thank you very much deanperry :)

**Comment by JIAZHEN** [comment]
I suggest to reopen this issue as the tutorial website is yet updated. http://tryshoppe.com/docs/tutorials/setting-up

**Comment by deanperry** [comment]
Just updated the docs :)
