### ISSUE TITLE
NoMethodError (undefined method `short_description' for #<Shoppe::ProductCategory::Translation:0x007fbb720893e8>):

### ISSUE THREAD

**Issue by shane51** [tryshoppe/shoppe#227]
I have an issue when "submit" a product category with newest version of Shoppe v1.0.9.
It throws error.
```
NoMethodError (undefined method `short_description' for #<Shoppe::ProductCategory::Translation:0x007fbb720893e8>):
```
After checking the source code, under shoppe/app/models/shoppe/product_category.rb:
```
translates :name, :permalink, :description, :short_description
```
Where ":short_description" should not be expected for product_category, I'm guessing this cause the error when Shoppe try to save it.

Does anyone has the same issue?

Thanks,

**Comment by deanperry** [comment]
v1.1.0 is now released with this fix :smile:
