### ISSUE TITLE
Product category images (after migration to 'attachments')

### ISSUE THREAD

**Issue by andretanguy** [tryshoppe/shoppe#229]
There's a bug been introduced after the migration from nifty-attachments to carrierwave. For products, images are uploadable and working fine, however product category images do upload in the backend:

http://screens.oceanshq.com/Screen%20Shot%202015-07-07%20at%2019.46.28.png

**Comment by deanperry** [comment]
Hi Andre,

OK I'll see if I can look at that either tonight or tomorrow.

Thanks!
Dean

André Tanguy wrote:

**Comment by deanperry** [comment]
v1.1.0 is now released with this fix :smile:
