### ISSUE TITLE
Reg:- Backend Naviagtions issues

### ISSUE THREAD

**Issue by Ramesh-Palanivel** [tryshoppe/shoppe#232]
Hi ,
I have added in this file one more navigation. called "Upload" but i got errors called upload_path is undefined, How to configure customized route path for back end.

file: lib/shoppe/default_navigation.rb
Shoppe::NavigationManager.build(:admin_primary) do
add_item :upload
end

Please let me know, how to configure customized route path 

Thanks in advance

**Comment by deanperry** [comment]
You'd need to fork the gem and modify it if you want to add some extra features
