### ISSUE TITLE
Issue with /shoppe/orders

### ISSUE THREAD

**Issue by ikhakoo** [tryshoppe/shoppe#237]
Getting an error with:

undefined method `entry_name' for #<Shoppe::Order::ActiveRecord_Relation:0x007f9c74112930>

Tried dropping the db and doing a shoppe:setup but that doesnt fix the issue.

Happening both locally and on heroku.  Is anyone else experiencing this issue?

https://github.com/ikhakoo/ap is the repo for the project

**Comment by deanperry** [comment]
This may be if you have the `will_paginate` gem. See this - http://stackoverflow.com/questions/14524091/why-this-pagination-doesnt-work-when-using-kaminari

**Comment by ikhakoo** [comment]
Closing this

**Comment by ikhakoo** [comment]
using will paginate ... thanks dean just saw that we literally posted at the same time! thanks!

**Comment by deanperry** [comment]
Ha :smile:

**Comment by ikhakoo** [comment]
could you recommend another method for pagination

**Comment by deanperry** [comment]
Shoppe is using Kaminari so it may be best to use that?  https://github.com/amatsuda/kaminari#usage

**Comment by ikhakoo** [comment]
ahh thanks sorry just re-read the post again ... its been a long day
