### ISSUE TITLE
Invalid validation for phone number

### ISSUE THREAD

**Issue by thierry-rietsch** [tryshoppe/shoppe#239]
Hey!

The current validation for the phone number is not valid. E.g. a phone number "+41 11 111 11 11" is a valid phone number but gets rejected by the current regex. I think it is quite hard to have a validation in place that works for all kind of different numbers (see for example http://stackoverflow.com/questions/123559/a-comprehensive-regex-for-phone-number-validation which covers a lot of US stuff, which is totally different on how we write phone numbers). My suggestion would be to remove the validation or make it optional, so that everyone can decide on his own, if he would like to have a validated phone number or not.

Thanks for your great work!
Thierry

**Comment by deanperry** [comment]
This should now be sorted with #276. I'll push a gem update shortly

**Comment by thierry-rietsch** [comment]
@deanperry Do you have any plan when you are going to push the gem update?
