### ISSUE TITLE
Issue with aws-fog

### ISSUE THREAD

**Issue by zoesteinkamp** [tryshoppe/shoppe#240]
I am trying to bundle the gem and I keep receiving this error. 

Bundler::GemspecError: Could not read gem at /Users/Zoe/.rvm/gems/ruby-2.2.1/cache/fog-aws-0.7.3.gem. It may be corrupted.
An error occurred while installing fog-aws (0.7.3), and Bundler cannot continue.
Make sure that `gem install fog-aws -v '0.7.3'` succeeds before bundling.

Does this have something to do with shoppe? Because its the only time im receiving the error is with this gem.

**Comment by deanperry** [comment]
Nope it shouldn't be. It looks like the gem that was downloaded is corrupted. Just delete that cached gem and try again
