### ISSUE TITLE
Product variants?

### ISSUE THREAD

**Issue by arturenault** [tryshoppe/shoppe#242]
Hi all,

I'm trying to set up product variants in my shoppe store. I see that there is the infrastructure in the rails gem to have product variants through the variants controller and model, but I can't find anything of that effect in the admin panel. Do they need to be enabled in some way?

Variants are very important to my store since it will be selling clothing and will thus need options for colors and sizes; it also will not be managed by programmers so I can't rely on calling the API all the time.

Thanks,
Artur

**Comment by ikhakoo** [comment]
@arturenault - I have had the same issue but have solved this using variants. if you look at my repo https://github.cm/ikhakoo/ap in the seeds file you will see how i seed in both parent products and variants.

Alternatively, you can go to /shoppe/products 

Add a product. Then select the product from the list and in the top right hand corner you will see a button called variants where you can then add variants in.

**Comment by arturenault** [comment]
For some reason I totally missed that button. Thanks a bunch!

I'm still getting a weird error when I try to create a new variant, though:

```
No route matches {:action=>"index", :controller=>"shoppe/product_localisations", :product_id=>#<Shoppe::Product id: nil, parent_id: 1, name: nil, sku: nil, permalink: nil, description: nil, short_description: nil, active: true, weight: #<BigDecimal:7f8ee3043778,'0.0',9(18)>, price: #<BigDecimal:7f8ee30435c0,'0.0',9(18)>, cost_price: #<BigDecimal:7f8ee3043408,'0.0',9(18)>, tax_rate_id: nil, created_at: nil, updated_at: nil, featured: false, in_the_box: nil, stock_control: true, default: false>} missing required keys: [:product_id]
```

I've tried redoing all the database migrations and setup steps, but that doesn't seem to solve it.

**Comment by ikhakoo** [comment]
Create a route in your routes file that matches the one you are calling.

**Comment by arturenault** [comment]
The route is within the shoppe admin panel though. Shouldn't that be handled by shoppe:setup?

**Comment by ikhakoo** [comment]
That's weird. Do you have the mount Shoppe thing in your routes ?

**Comment by arturenault** [comment]
Yup.
```mount Shoppe::Engine => "/shoppe"```

**Comment by deanperry** [comment]
What version of Shoppe are you using?

**Comment by arturenault** [comment]
1.1.0

**Comment by ikhakoo** [comment]
Try updating your rails version

**Comment by arturenault** [comment]
No dice, was already at the latest one.

Could this be a locale issue? I've run into those before.

**Comment by arturenault** [comment]
Doesn't sound like a locale issue, the translation function is fine.

I narrowed down the issue to the fact that it's trying to generate a route for variants#new but apparently the product_id is not getting passed in (```missing required keys: [:product_id]```), which is not getting passed in for some reason. Looking back at the code snippet I posted before, nearly all parameters for the products are null; isn't this expected in the "new" action?

**Comment by tr0ythex** [comment]
Hello. I have the same issue here. When I try to add a variant I get an error:
`No route matches {:action=>"index", :controller=>"shoppe/product_localisations", :product_id=>#<Shoppe::Product id: nil, parent_id: 5, name: nil, sku: nil, permalink: nil, description: nil, short_description: nil, active: true, weight: #<BigDecimal:7fe5dfc2eb70,'0.0',9(18)>, price: #<BigDecimal:7fe5dfc2e9b8,'0.0',9(18)>, cost_price: #<BigDecimal:7fe5dfc2e800,'0.0',9(18)>, tax_rate_id: nil, created_at: nil, updated_at: nil, featured: false, in_the_box: nil, stock_control: true, default: false>} missing required keys: [:product_id]`

**Comment by jprof7** [comment]
There was a commit https://github.com/tryshoppe/shoppe/commit/42ea93107c3261ff0052cf7e0c4a9a0802c6ee7e that added the link to `/app/views/shoppe/variants/form.html.haml` (line 4) for variant localizations, but it doesn't appear that a corresponding route was added, and possibly not a controller for it either (didn't dig too deep for it).

**Comment by arturenault** [comment]
Yeah, that's working for me too. I'll switch back to 1.0.7 for now but this should really be fixed

**Comment by iDuuck** [comment]
Also had the same problem with the error message. Fixed it, when creating a new file `app/views/shoppe/variants/form.html.haml` and added the content of the original file and just removed the line (works for me).

**Comment by deanperry** [comment]
Ok can you create a PR and I'll accept it?

**Comment by iDuuck** [comment]
Done!
