### ISSUE TITLE
Using carrierwave

### ISSUE THREAD

**Issue by ikhakoo** [tryshoppe/shoppe#243]
One of the things i have in my site is size charts and as such I installed the carrierwave gem to handle the extra files.  What I noticed was that product images through shoppe are rendering just fine on heroku but carrierwave images are not.  I was under the impression that shoppe is using carrierwave although I haven't verified this yet.  Any ideas on the best way to make this work so I can host my images without having to point them to AWS or anywhere else?

**Comment by deanperry** [comment]
Yep, to setup Carrierwave use this tutorial http://tryshoppe.com/docs/attachments

**Comment by ikhakoo** [comment]
would this work on 1.0.5 as well ? I see it is updated for 1.0.9.

The reason I ask is because i can not upgrade at this time because I made many personal customizations based on the clients needs.

**Comment by deanperry** [comment]
In that case no, you'd have to copy the changes over as we are now using an attachment model 

Sent from Outlook




On Tue, Jul 28, 2015 at 3:43 PM -0700, "Imran Khakoo" <notifications@github.com> wrote:












would this work on 1.0.5 as well ? I see it is updated for 1.0.9.



The reason I ask is because i can not upgrade at this time because I made many personal customizations based on the clients needs.

**Comment by ikhakoo** [comment]
What do you think would be the best way for me to serve my image files as well like you did for the product images?

**Comment by deanperry** [comment]
Depending on what changes you've made, you may be better off merging your version with the latest code

Sent from Outlook




On Tue, Jul 28, 2015 at 4:08 PM -0700, "Imran Khakoo" <notifications@github.com> wrote:












What do you think would be the best way for me to serve my image files as well like you did for the product images?

**Comment by ikhakoo** [comment]
I made some major changes that will most likely break the app should I upgrade. I don't plan on doing an upgrade until the owner requests the second version and I need to deliver v1 in like 2 days so rebuilding would be a massive issue at this time. :(

**Comment by ikhakoo** [comment]
I am closing this issue as i resolved it by using information provided on the carrierwave gem page.
