### ISSUE TITLE
Couldn't find Shoppe::Product

### ISSUE THREAD

**Issue by occult** [tryshoppe/shoppe#246]
Can anyone tell me why this won't work? I copied it directly from the [official tutorial](http://tryshoppe.com/docs/tutorials/baskets).

```
def buy
    @product = Shoppe::Product.find_by_permalink!(params[:permalink]) #This is the line that wont work
    current_order.order_items.add_item(@product, 1)
    redirect_to product_path(@product.permalink), :notice => "Product has been added successfuly!"
end
```
P.S. I have ran all the generators such as `rake db:migrate shoppe:setup `.

**Comment by deanperry** [comment]
What if you do  `Shoppe::Product.root.find_by_permalink`

**Comment by occult** [comment]
@deanperry You're amazing! Why does my code not work though?

**Comment by deanperry** [comment]
OK I'll have to update those docs. What's the issue you're having? It's more than likely that the product doesn't have any stock

**Comment by occult** [comment]
@deanperry My product is working fine, I was just wondering why `@product = Shoppe::Product.find_by_permalink!(params[:permalink])` doesn't work.
