### ISSUE TITLE
Error with moving from v1.0.5 to higher

### ISSUE THREAD

**Issue by OlegTurbal** [tryshoppe/shoppe#248]
Error with applying migration 20141026181717_allow_multiple_shoppe_products_per_shoppe_product_category.rb for products with variants.
Trace:
== 20141026181717 AllowMultipleShoppeProductsPerShoppeProductCategory: migrating 
-- create_table(:shoppe_product_categorizations)
   -> 0.0381s
-- add_index(:shoppe_product_categorizations, :product_id, {:name=>"categorization_by_product_id"})
   -> 0.0616s
-- add_index(:shoppe_product_categorizations, :product_category_id, {:name=>"categorization_by_product_category_id"})
   -> 0.0475s
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Shoppe::ProductCategory(#70288885455800) expected, got NilClass(#70288851531640)

**Comment by deanperry** [comment]
Apologies for the delay. Is this on a current app which already has products?
