### ISSUE TITLE
Overwrite the email views?

### ISSUE THREAD

**Issue by jsantana90** [tryshoppe/shoppe#250]
Is there a way to edit the views for the emails being sent by shoppe? I would like to add an attachment to the email when you accept the order.

Thanks!

**Comment by deanperry** [comment]
Not currently but you can fork the gem to modify the mailer and use your version

**Comment by jsantana90** [comment]
ah, ok, I manage to just copy and paste the exact names of the directories and views in the rails app and that did the trick, at least for the models and mail views. Would be a nice version update to add a generator for those features in the future.
