### ISSUE TITLE
Shoppe (Rails) App: "uninitialized constant Shoppe"

### ISSUE THREAD

**Issue by emilyliuu** [tryshoppe/shoppe#252]
Hi, pretty new to rails and starting my first Shoppe App. I've followed the steps on their get started page (http://tryshoppe.com/docs/tutorials/setting-up), and after running the server, it's giving me an "uninitialized constant Shoppe" error with the line "  mount Shoppe::Engine => "/shoppe" " in routes.rb. Anyone know how to fix that and why that would happen? Thanks!

**Comment by deanperry** [comment]
It doesn't sound like you have the Shoppe gem in your Gemfile and ran bundle install
