### ISSUE TITLE
No validation for billing_address2

### ISSUE THREAD

**Issue by tr0ythex** [tryshoppe/shoppe#253]
Hello.
I noticed that in order/billing.rb there's no presence validation only for billing_address2. Is that ok?

**Comment by desiby** [comment]
I would add it on the front end may be?

**Comment by tr0ythex** [comment]
Yes, I think I can add it on front end. Also I can remove all billing_address fields except billing_address1. But it's strange than exactly billing_address2 absent in code

**Comment by deanperry** [comment]
It's the same as delivery_address2. Some times all the fields aren't required.
