### ISSUE TITLE
Unable to autoload constant NotificationMailer, expected app/mailers/notification_mailer.rb to define it

### ISSUE THREAD

**Issue by jsantana90** [tryshoppe/shoppe#254]
I am following the website tutorial http://tryshoppe.com/docs/extending to help me create the notification for the staff members, but every time I submit an order I get this error.

I'm calling the gem using `gem 'shoppe-notification', :path => 'shoppe-notification'`

What am I doing wrong?
![screenshot from 2015-08-26 13 47 30](https://cloud.githubusercontent.com/assets/9933887/9501378/03f24b42-4bf9-11e5-9acb-a197aa810b0d.png)

**Comment by jsantana90** [comment]
just typos

**Comment by deanperry** [comment]
Ha, no problems
