### ISSUE TITLE
undefined method `keys' for "translation missing: es-US.shoppe.settings.defaults":String

### ISSUE THREAD

**Issue by jsantana90** [tryshoppe/shoppe#257]
When I try to access the shoppe admin interface and my locale was `es-US` it gives me this error, it will not give me any errors if my locale was `en`.

**Comment by deanperry** [comment]
How are you setting the locale? These are currently the locales used  https://github.com/tryshoppe/shoppe/tree/master/config/locales

**Comment by jsantana90** [comment]
ah I see, so I'll have to create a custom one.

Also, how do I change that when I am in `es` the prices changes from, for example `4.99` to `4,99` I don't want it to have a coma.

**Comment by jsantana90** [comment]
hmm ok, so I was just able to fork the gem and duplicate the `es.yml` into `es-US.yml` and that seems to fix everything except a part in the translation that is missing in the `es.yml` which is `customer` which is missing in that file. Just to let you know

```
admin_primary:
        customers: Clientes
```

**Comment by deanperry** [comment]
Feel free to submit a pull request :)

On 26 August 2015 at 21:57, jsantana90 <notifications@github.com> wrote:

> hmm ok, so I was just able to fork the gem and duplicate the es.yml into
> es-US.yml and that seems to fix everything except a part in the
> translation that is missing in the es.yml which is customer which is
> missing in that file. Just to let you know
>
> admin_primary:
>         customers: Clientes
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tryshoppe/shoppe/issues/257#issuecomment-135168388>.
>



-- 
Kind Regards,
Dean Perry

http://deanpcmad.com
@DeanPerry <https://twitter.com/DeanPerry>

**Comment by jsantana90** [comment]
my first time doing one, let me see if I can do it right lol
