### ISSUE TITLE
"Billing country can't be blank"

### ISSUE THREAD

**Issue by desiby** [tryshoppe/shoppe#259]
I get a "Billing country can't be blank" validation error message in the check out view. The country field is absent in the view though present in the code from the documentation.

```
<h2>Checkout</h2>
<%= render 'items', :order => @order %>

<%= form_for @order, :url => checkout_path do |f| %>

<dl>
    <dt><%= f.label :first_name, 'Name' %></dt>
    <dd><%= f.text_field :first_name %> <%= f.text_field :last_name %></dd>

    <dt><%= f.label :billing_address1, 'Address' %></dt>
    <dd><%= f.text_field :billing_address1 %></dd>
    <dd><%= f.text_field :billing_address2 %></dd>
    <dd><%= f.text_field :billing_address3 %></dd>
    <dd><%= f.text_field :billing_address4 %></dd>
    <dt><%= f.label :billing_postcode, 'Post code' %></dt>
    <dd><%= f.text_field :billing_postcode %></dd>
    <dd><%= f.collection_select :billing_country_id, Shoppe::Country.ordered, :id, :name, :include_blank => true %></dd>

    <dt><%= f.label :email_address %></dt>
    <dd><%= f.text_field :email_address %></dd>

    <dt><%= f.label :phone_number %></dt>
    <dd><%= f.text_field :phone_number %></dd>

    <dd><%= f.submit 'Continue' %></dd>
  </dl>
<% end %>
```

![screenshot from 2015-08-28 23 36 44](https://cloud.githubusercontent.com/assets/12163470/9560375/ba4147a0-4ddd-11e5-9ec0-45f574e95622.png)

should I run a migration to fix this? how do you fix it?

**Comment by deanperry** [comment]
Is the billing_country_id added to the safe params in your controller?

**Comment by desiby** [comment]
yes the billing_country_id is in the safe params of the checkout action of the orders controller
def checkout
        @order = Shoppe::Order.find(current_order.id)
        if request.patch?
            if @order.proceed_to_confirm(params[:order].permit(:first_name, :last_name, :billing_address1, :billing_address2, :billing_address3, :billing_address4, :billing_country_id, :billing_postcode, :email_address, :phone_number))
                   redirect_to checkout_payment_path
            end
        end
    end

**Comment by deanperry** [comment]
OK and I guess the `billing_country_id` is present when being confirmed? Shoppe has a set of countries that can be imported

**Comment by desiby** [comment]
There isn't even a "billing country" field in the view, don't know if I have to modify the code provided in the documentation
in the view:
<dd><%= f.collection_select :billing_country_id, Shoppe::Country.ordered, :id, :name, :include_blank => true %></dd>

**Comment by deanperry** [comment]
If you've followed the tutorial then you should have - http://tryshoppe.com/docs/tutorials/checking-out
