### ISSUE TITLE
Validation for delivery service

### ISSUE THREAD

**Issue by occult** [tryshoppe/shoppe#260]
I followed the tutorial at [the Shoppe website](http://tryshoppe.com/docs/tutorials/checking-out) step by step, but when I proceed to payment it tells me I have to define a delivery service. I tried making a form field with `:courier` but that didn't work either. 

Thanks in advance for any help :smile:

**Comment by deanperry** [comment]
If you've run the first setup rake tasks and assigned delivery services for the weight of the product you are selling, the list of delivery services available will show on the basket page - http://tryshoppe.com/docs/tutorials/baskets
