### ISSUE TITLE
Carrierwave not working with S3

### ISSUE THREAD

**Issue by juan267** [tryshoppe/shoppe#265]
im using shoppe for a e-commerce site hosted on Heroku, right now when I upload images to products or product categories the pictures appear initially but after a while they disappear. This is because Heroku doesn't store images and they get deleted after the server is restarted or when I do a push to production,  so I wanted to upload the images to S3 using the new carrierwave integration with shoppe but with no success. 

I currently have the following initializer :

``` ruby
CarrierWave.configure do |cfg|
  if Rails.env.production?
    cfg.storage = :fog
    cfg.fog_credentials = {
      :provider               => 'AWS',
      :aws_access_key_id      => ENV["AWS_ACCESS_ID"],
      :aws_secret_access_key  => ENV["AWS_ACCESS_SECRET"]
    }
    cfg.fog_directory  = ENV["AWS_BUCKET"]
    cfg.fog_public     = true
    cfg.fog_attributes = {'Cache-Control'=>'max-age=315576000'}
  else
    cfg.storage = :file
  end

  cfg.enable_processing = !Rails.env.test?
end
```

And all my environment variables are correctly configure on Heroku with a valid account on AWS with permissions to have all access to S3. Is there something that Im missing?

**Comment by juan267** [comment]
Ok, so i fix this.  It seems that this line `cfg.storage = :fog` does not work if you have this other line ` storage :file` already configure in the attachment_uploader.rb file in the shoppe engine. So when you remove that line from the uoloader file  `cfg.storage = :fog`  does work in the initializer. This raises the problem that i had to modified shoppe source code to fix the problem and that if i post a pull request with this fix it would be necessary to change the documentation to always include the carrierwave initializer to set the correct storage option depending on the rails environment.  Either Im going to submit it so you guys decide if you would like to include this fix to the source code, or if you have a better solution than mine.

**Comment by deanperry** [comment]
Ok looks like I need to add an option in the documentation
