### ISSUE TITLE
Missing required keys (permalink) when setting default locale in application.rb

### ISSUE THREAD

**Issue by tr0ythex** [tryshoppe/shoppe#267]
Hello. The problem appears when I try to set default locale in application.rb file:
`config.i18n.default_locale = :ru`
`config.i18n.default_locale = :de` 
or even `config.i18n.default_locale = :en`
The index page crashes with the following error:
**No route matches {:action=>"show", :controller=>"products", :permalink=>nil} missing required keys: [:permalink]**
`<h4><%= link_to product.name, product_path(product.permalink) %></h4>`
What should I do in this situation? Help please

**Comment by tr0ythex** [comment]
I found solution:
In admin cosole I created localizations for all products and It has worked.

**Comment by pavan461** [comment]
HI @tr0ythex i'm also facing this kind of issue, in product_categories, can you explain me how to fix this issue?
