### ISSUE TITLE
Documentation error in Method Buy

### ISSUE THREAD

**Issue by Awce** [tryshoppe/shoppe#270]
def buy
  @product = Shoppe::Product.find_by_permalink!(params[:permalink])
  current_order.order_items.add_item(@product, 1)
  redirect_to product_path(@product.permalink), :notice => "Product has been added successfuly!"
end

for

def buy
  @product = Shoppe::Product.root.find_by_permalink!(params[:permalink])
  current_order.order_items.add_item(@product, 1)
  redirect_to product_path(@product.permalink), :notice => "Product has been added successfuly!"
end

**Comment by deanperry** [comment]
Ok so `Shoppe::Product` should be changed to `Shoppe::Product.root`? I'll update the docs.

**Comment by Awce** [comment]
Thank you!

**Comment by sbhshkmr674** [comment]
I am having error at code " current_order.order_items.add_item(@product, 1)".
please help me out from this problem and thanks in advance.
Shoppe::Errors::UnorderableItem in ProductsController#buy
Extracted source (around line #13):

11
12
13
14
15
16
              

	

  def buy
  @product = Shoppe::Product.root.find_by_permalink!(params[:permalink])
  current_order.order_items.add_item(@product, 1)
  redirect_to product_path(@product.permalink), :notice => "Product has been added successfuly!"
  end 
end

Rails.root: /home/subhash/rails_apps/widget_shop
