### ISSUE TITLE
Using my site's user model rather than Shoppe's

### ISSUE THREAD

**Issue by kimadactyl** [tryshoppe/shoppe#272]
How would I go about using my own user model for authentication? It looks like there's the framework for this in #118 and #119 but new to Rails and struggling to work out how to wire stuff up.

My main needs for this are twofold:

 * I want my existing user model to simple have an "is_shoppe_admin" attribute so there's no need for a second set of login info etc.
 * I want to sell access to online content and want the flexibility to make my signup/payment as painful as possible and assign attributes to the user based on what they buy. 

Thanks!

**Comment by deanperry** [comment]
Currently using a separate model isn't supported. There is a customer model
where orders are linked to however

**Comment by kimadactyl** [comment]
OK! Is there a way I can solve my first question, i.e. using my own authentication to access the backend? Or is that tied in too closely to the accepter logic?

**Comment by deanperry** [comment]
Unfortunately not unless you fork the gem and modify the sessions
controller to use your User model

**Comment by kimadactyl** [comment]
OK, no worries. Will have a go and see where I get. Thanks!

**Comment by deanperry** [comment]
@kimadactyl please see the updates on #273
