### ISSUE TITLE
No Accounts for customers?

### ISSUE THREAD

**Issue by msumeet** [tryshoppe/shoppe#273]
Hi,

Looks like there are no accounts feature for customers. So what customers stands in admin of shoppe where we can see customers list? Any way to integrate user accounts system in shoppe?

Thanks.

**Comment by deanperry** [comment]
How do you mean? Is this similar to #272

**Comment by msumeet** [comment]
Hi, I want the feature where users can create account so they can see their past orders, track their purchases easily, add their addresses. I need a way where users can  sign in & sign out. Quite similar to #272 .

**Comment by msumeet** [comment]
Hi, any update on this? Can I use devise for users login & logout. I need an feature where users can log in and see their past order history etc.

**Comment by deanperry** [comment]
The customer model is basic so you can modify it to how you want it

**Comment by deanperry** [comment]
You could add devise to your app and then do the following

- Create a User model with Devise with a `customer_id` field
- Add `belongs_to :customer, class: Shoppe::Customer` to User model
- Create a Customer record on signup and use that for orders

**Comment by msumeet** [comment]
@deanperry 
Thank you so much. I will add it. One more question, after following this - whenever an account will be created it will automatically shown in the admin panel?

**Comment by deanperry** [comment]
Yep Customers are shown in the admin. Users you create with Devise won't be however

**Comment by samueladesoga** [comment]
Guys, i dont know if this helps i have been able to do this, worked around extending the Shoppe::Customer Model witrh devise.

`require_dependency Shoppe::Engine.root.join('app', 'models', 'shoppe', 'customer').to_s

module Shoppe
  class Customer < ActiveRecord::Base
  	devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  end
end`

also the migration has been tweaked to change_table and not create_table

`class DeviseCreateShoppeCustomers < ActiveRecord::Migration
  def change
    change_table :shoppe_customers do |t|
      ## Database authenticatable
      t.string :encrypted_password, null: false, default: ""

      ## Recoverable
      t.string   :reset_password_token
      t.datetime :reset_password_sent_at

      ## Rememberable
      t.datetime :remember_created_at

      ## Trackable
      t.integer  :sign_in_count, default: 0, null: false
      t.datetime :current_sign_in_at
      t.datetime :last_sign_in_at
      t.inet     :current_sign_in_ip
      t.inet     :last_sign_in_ip

      ## Confirmable
      t.string   :confirmation_token
      t.datetime :confirmed_at
      t.datetime :confirmation_sent_at
      t.string   :unconfirmed_email # Only if using reconfirmable

      ## Lockable
      # t.integer  :failed_attempts, default: 0, null: false # Only if lock strategy is :failed_attempts
      # t.string   :unlock_token # Only if unlock strategy is :email or :both
      # t.datetime :locked_at
    end

    add_index :shoppe_customers, :email,                unique: true
    add_index :shoppe_customers, :reset_password_token, unique: true
    # add_index :shoppe_customers, :confirmation_token,   unique: true
    # add_index :shoppe_customers, :unlock_token,         unique: true
  end
end
`

This seems to work for me ..

**Comment by pranavpr** [comment]
@samueladesoga : You also need to add this line in `routes.rb`

`devise_for :shoppe_customers, class_name: Shoppe::Customer`
