### ISSUE TITLE
Product Importing does not work after changes to product categories

### ISSUE THREAD

**Issue by andretanguy** [tryshoppe/shoppe#274]
Enabling a product to be assigned to multiple categories has introduced a breaking change in the import module:

http://screens.oceanshq.com/Screen%20Shot%202015-09-19%20at%2021.41.24.png

**Comment by andretanguy** [comment]
For further information, the sample spreadsheet format was used: http://screens.oceanshq.com/Screen%20Shot%202015-09-19%20at%2021.46.48.png

**Comment by deanperry** [comment]
Ok no problems, I'll take a look
