### ISSUE TITLE
There's no translation for the Customers section in admin interface

### ISSUE THREAD

**Issue by tr0ythex** [tryshoppe/shoppe#275]
Hello. I try to make a russian translation for shoppe. I translated whole en.yml file to ru.yml and there is one section that has not been translated. It's Customers section.
I also checked this on de and es locales. The same thing there.

**Comment by deanperry** [comment]
Ok I'll see if I can move that over to the English locale. You can create a PR if you want?

**Comment by tr0ythex** [comment]
Ok, should I also add ru.yml file in that PR?

**Comment by deanperry** [comment]
Yep you can do
