### ISSUE TITLE
Migration fails with 'cannot load such file'

### ISSUE THREAD

**Issue by Collibhoy** [tryshoppe/shoppe#297]
Following the instructions in the documentation, the migration fails as follows;

LoadError: cannot load such file -- /Library/Ruby/Gems/2.0.0/gems/shoppe-1.1.1/app/models/shoppe/product.rb

**Comment by chrztoph** [comment]
Can you provide an example (github repo) of your project?

**Comment by listik-cveta** [comment]
I have same problem.
After "rake db:migrate shoppe:setup":

rake aborted!
LoadError: cannot load such file -- /usr/local/rvm/gems/ruby-2.1.5/gems/shoppe-1.1.1/app/models/shoppe/product.rb

**Comment by deanperry** [comment]
I can't replicate this. What of Rails are you using?

**Comment by listik-cveta** [comment]
Hey! After pain of my mind, i fix this problem like this: "touch /usr/local/rvm/gems/ruby-2.1.5/gems/shoppe-1.1.1/app/models/shoppe/product.rb" and chmod 660 this file. Profit!

**Comment by listik-cveta** [comment]
My rails version is 4.2.4, but i'd tried 4.1.* and 4.0.*. Only touch product.rb fix problem.

**Comment by deanperry** [comment]
Ok that's odd. It sounds like the shoppe gem hasn't installed properly on your machine then 





On Sun, Nov 8, 2015 at 11:09 PM -0800, "listik-cveta" <notifications@github.com> wrote:












My rails version is 4.2.4, but i'd tried 4.1.* and 4.0.*. Only touch product.rb fix problem.

**Comment by Collibhoy** [comment]
product.rb file existed for me, chmod 755 fixed the problem.  Permissions on install must have been messed up.

**Comment by Collibhoy** [comment]
@deanperry I just wanted to add some more information to this problem.  It first occurred on my Mac, and then I installed today on a Linux Ubuntu VM and got the same problem.  The product.rb file existed after the gem install but I had to again chmod 755 to allow the rake db:migrate shoppe:setup command to work.  Perhaps the file isn't being given correct permissions on install?
