### ISSUE TITLE
Missing Dependency ImageMagick/GraphicsMagick

### ISSUE THREAD

**Issue by syaiful6** [tryshoppe/shoppe#298]
While i try shoppe, and follow the tutorial in tryshoppe, i got error when on route product#new
the details attached. I solve it by install it manually, look like the dependency not installed automatically, if it used by shoppe when build new product i think it should installed automatically. :)

By the way, I love this gem though.

![screenshot 14](https://cloud.githubusercontent.com/assets/2830977/10722898/eb312cc6-7be7-11e5-8658-325a07adde6c.png)

**Comment by koenpunt** [comment]
I don't believe installing automatically is an option, as the backend is configurable. Some like imagemagick over grapghicsmagic, some the other way around. So there is no best guess.

If any gem would be installing the actual library, it should be the IM or GM gem itself, not shoppe.

**Comment by deanperry** [comment]
Yep you'll need to install ImageMagick. I have no experience with running Rails on Windows but you can download IM from their site - http://www.imagemagick.org/script/binary-releases.php#windows
