### ISSUE TITLE
Carrierwave not working with S3 even i tried all the way

### ISSUE THREAD

**Issue by shyammohankanojia** [tryshoppe/shoppe#301]
Carrierwave not working with S3 even i tried all the way
Can anyone help here?

**Comment by shyammohankanojia** [comment]
I using all the latest setup and tried http://tryshoppe.com/docs/attachments

**Comment by deanperry** [comment]
What issue are you having, items aren't being saved on S3 but they are being saved to the database? What version of Shoppe are you using?

**Comment by shyammohankanojia** [comment]
items aren't being saved on S3 but they are being saved to the database and local storage. Even i removed file storage type.

shoppe version 1.1.1
Rails 4.2.4
Ruby 2.2.3
carrierwave (0.10.0)

**Comment by deanperry** [comment]
If you've followed the [attachments docs](http://tryshoppe.com/docs/attachments) then S3 won't work in development. If you want it to, then comment out the if Rails.env.production code

**Comment by shyammohankanojia** [comment]
Thanks for your advise, but this is basic thing to do if we need to test in development.

**Comment by deanperry** [comment]
It does say in the docs that it is production only by default unless you slightly change it
