### ISSUE TITLE
associate customer with user

### ISSUE THREAD

**Issue by iqbalhasnan** [tryshoppe/shoppe#305]
is there any work in progress to associate `Customer` with `User` so we can allow customer to authenticate themselves?

I read in this PR https://github.com/tryshoppe/shoppe/pull/119 that polymorphic association is favorable so that we can associate any of their models with a customer.

I can start implementing this if we agree to go with this approach.

**Comment by deanperry** [comment]
This would be up to the user in their own apps but if you want to write the docs for it at https://github.com/tryshoppe/documentation that would be great
