### ISSUE TITLE
Rails Server 

### ISSUE THREAD

**Issue by andreavecy** [tryshoppe/shoppe#308]
andreavecino@andreavecino-HP-Pavilion-Sleekbook-14:~/Documentos/accendosas$ rails server
=> Booting WEBrick
=> Rails 4.2.4 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
/home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:557:in `add_route': Invalid route name, already in use: 'shoppe'  (ArgumentError)
You may have defined two routes with the same name using the `:as` option, or you may be overriding a route already defined by a resource with the same naming. For the latter, you can restrict the routes created with `resources` as explained here: 
http://guides.rubyonrails.org/routing.html#restricting-the-routes-created
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:1561:in `add_route'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:1536:in `decomposed_match'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:1517:in `block in match'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:1507:in `each'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:1507:in `match'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:588:in `mount'
	from /home/andreavecino/Documentos/accendosas/config/routes.rb:11:in `block in <top (required)>'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:434:in `instance_exec'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:434:in `eval_block'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:412:in `draw'
	from /home/andreavecino/Documentos/accendosas/config/routes.rb:1:in `<top (required)>'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:40:in `each'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:40:in `load_paths'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:16:in `reload!'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:26:in `block in updater'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/activesupport-4.2.4/lib/active_support/file_update_checker.rb:75:in `call'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/activesupport-4.2.4/lib/active_support/file_update_checker.rb:75:in `execute'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:27:in `updater'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/railties-4.2.4/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `run'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/railties-4.2.4/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/andreavecino/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
	from /home/andreavecino/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /home/andreavecino/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
	from /home/andreavecino/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /home/andreavecino/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:345:in `each'
	from /home/andreavecino/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:345:in `call'
	from /home/andreavecino/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
	from /home/andreavecino/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
	from /home/andreavecino/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/railties-4.2.4/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/railties-4.2.4/lib/rails/application.rb:352:in `initialize!'
	from /home/andreavecino/Documentos/accendosas/config/environment.rb:5:in `<top (required)>'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /home/andreavecino/Documentos/accendosas/config.ru:3:in `block in <main>'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from /home/andreavecino/Documentos/accendosas/config.ru:in `new'
	from /home/andreavecino/Documentos/accendosas/config.ru:in `<main>'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/railties-4.2.4/lib/rails/commands/server.rb:61:in `app'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/railties-4.2.4/lib/rails/commands/server.rb:139:in `log_to_stdout'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/railties-4.2.4/lib/rails/commands/server.rb:78:in `start'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/andreavecino/Documentos/accendosas/bin/rails:8:in `require'
	from /home/andreavecino/Documentos/accendosas/bin/rails:8:in `<top (required)>'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/spring-1.4.0/lib/spring/client/rails.rb:28:in `load'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/spring-1.4.0/lib/spring/client/rails.rb:28:in `call'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/spring-1.4.0/lib/spring/client/command.rb:7:in `call'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/spring-1.4.0/lib/spring/client.rb:28:in `run'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/spring-1.4.0/bin/spring:49:in `<top (required)>'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/spring-1.4.0/lib/spring/binstub.rb:11:in `load'
	from /home/andreavecino/.rvm/gems/ruby-2.1.5@luxorial/gems/spring-1.4.0/lib/spring/binstub.rb:11:in `<top (required)>'
	from /home/andreavecino/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/andreavecino/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/andreavecino/Documentos/accendosas/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'

**Comment by deanperry** [comment]
As it says in the first error 

`Invalid route name, already in use: 'shoppe' (ArgumentError) You may have defined two routes with the same name using the:asoption, or you may be overriding a route already defined by a resource with the same naming. For the latter, you can restrict the routes created with resources as explained here: http://guides.rubyonrails.org/routing.html#restricting-the-routes-created`

It looks like you have the following code twice in your `routes.rb`

```ruby
mount Shoppe::Engine => "/shoppe"
```

**Comment by andreavecy** [comment]
thanks !!

**Comment by andreavecy** [comment]
def check_pending!(connection = Base.connection)
        raise ActiveRecord::PendingMigrationError if ActiveRecord::Migrator.needs_migration?(connection)
      end

      def load_schema_if_pending!

**Comment by deanperry** [comment]
That means you need to run the database migrations. I recommend reading through this site to learn Rails - https://www.railstutorial.org/
