### ISSUE TITLE
Please update Attachement Doc

### ISSUE THREAD

**Issue by ClementKerneur** [tryshoppe/shoppe#309]
Hello, the attachement doc http://tryshoppe.com/docs/attachments is obsolette with gem 'shoppe' of RubyGem 1.1.1
I use last version of shoppe on github to use :fog
gem 'shoppe', :git => 'https://github.com/tryshoppe/shoppe.git'

**Comment by deanperry** [comment]
Some people may still need it plus it also has information on converting to the new Attachment system & Fog
