### ISSUE TITLE
Language Shoppe

### ISSUE THREAD

**Issue by andreavecy** [tryshoppe/shoppe#311]
Is it possible to change the language to the Admin Page? I can't find any setting to do that.

**Comment by deanperry** [comment]
I believe this is set by your machine's default language. I personally haven't used I18n in my apps so I'm not sure but there are a number of languages that Shoppe supports

**Comment by andreavecy** [comment]
Where's Shoppe retrieving my locale? Because i'm 100% sure i have everything set to es_CO, but i still get english on the Admin page

**Comment by jasmo2** [comment]
@andreavecy I would like to do the same, 
Could you translate the admin page?

**Comment by andreavecy** [comment]
config/aplication.rb 
config.i18n.default_locale = :es
