### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by andreavecy** [tryshoppe/shoppe#318]
How I can generate models of the database ? because when the database is migrated Daton not bring models

**Comment by andreavecy** [comment]
i need add validation

**Comment by andreavecy** [comment]
i can copy de the models and paste in the project??

**Comment by deanperry** [comment]
How do you mean? The models are already there - https://github.com/tryshoppe/shoppe/tree/master/app/models/shoppe

**Comment by andreavecy** [comment]
creras when a new project and you migrate the database not migrated models

**Comment by andreavecy** [comment]
you can help me?
