### ISSUE TITLE
why do i always have such errors with double  Shoppe:: prefix  like 'uninitialized constant Shoppe::Shoppe::DeliveryServicePrice ' 

### ISSUE THREAD

**Issue by scalaview** [tryshoppe/shoppe#319]
CACHE (0.0ms)  SELECT SUM(`shoppe_stock_level_adjustments`.`adjustment`) FROM `shoppe_stock_level_adjustments` WHERE `shoppe_stock_level_adjustments`.`item_id` = 1 AND `shoppe_stock_level_adjustments`.`item_type` = 'Shoppe::Product'  [["item_id", 1], ["item_type", "Shoppe::Product"]]
  CACHE (0.0ms)  SELECT SUM(`shoppe_stock_level_adjustments`.`adjustment`) FROM `shoppe_stock_level_adjustments` WHERE `shoppe_stock_level_adjustments`.`parent_id` = 3 AND `shoppe_stock_level_adjustments`.`parent_type` = 'Shoppe::OrderItem'  [["parent_id", 3], ["parent_type", "Shoppe::OrderItem"]]
  SQL (0.4ms)  UPDATE `shoppe_order_items` SET `quantity` = 1, `updated_at` = '2015-12-08 15:36:57' WHERE `shoppe_order_items`.`id` = 3
  SQL (0.3ms)  UPDATE `shoppe_orders` SET `shoppe_orders`.`updated_at` = '2015-12-08 15:36:57' WHERE `shoppe_orders`.`id` = 2
  Shoppe::OrderItem Load (0.5ms)  SELECT `shoppe_order_items`.* FROM `shoppe_order_items` WHERE `shoppe_order_items`.`order_id` = 2
  Shoppe::Product Load (0.6ms)  SELECT  `shoppe_products`.* FROM `shoppe_products` WHERE `shoppe_products`.`id` = 1 LIMIT 1
  Shoppe::DeliveryServicePrice Load (2.4ms)  SELECT `shoppe_delivery_service_prices`.* FROM `shoppe_delivery_service_prices` INNER JOIN `shoppe_delivery_services` ON `shoppe_delivery_services`.`id` = `shoppe_delivery_service_prices`.`delivery_service_id` WHERE `shoppe_delivery_services`.`active` = 1 AND (min_weight <= 1.119 AND max_weight >= 1.119)  ORDER BY `shoppe_delivery_service_prices`.`price` ASC
  Shoppe::DeliveryService Load (0.7ms)  SELECT  `shoppe_delivery_services`.* FROM `shoppe_delivery_services` WHERE `shoppe_delivery_services`.`id` = 2 LIMIT 1
  Shoppe::DeliveryService Load (0.5ms)  SELECT  `shoppe_delivery_services`.* FROM `shoppe_delivery_services` WHERE `shoppe_delivery_services`.`id` = 1 LIMIT 1
  Shoppe::DeliveryService Load (0.4ms)  SELECT  `shoppe_delivery_services`.* FROM `shoppe_delivery_services` WHERE `shoppe_delivery_services`.`id` = 4 LIMIT 1
  Shoppe::DeliveryService Load (0.3ms)  SELECT  `shoppe_delivery_services`.* FROM `shoppe_delivery_services` WHERE `shoppe_delivery_services`.`id` = 3 LIMIT 1
uninitialized constant Shoppe::Shoppe::DeliveryServicePrice
   (0.8ms)  ROLLBACK
Completed 406 Not Acceptable in 5022ms (ActiveRecord: 49.2ms)

ruby version is ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]
Rails 4.2.4

**Comment by deanperry** [comment]
What version of Shoppe are you using? I've not seen this error before...

**Comment by scalaview** [comment]
hello,I have two computers,one of them has this problem and the anther one every thing fine. They have some environment but different OS,  I am very confuse

**Comment by deanperry** [comment]
Have you tried reinstalling the gem

**Comment by scalaview** [comment]
I had found the reason. In the model  shoppe/order/delivery.rb,  method: delivery_service_prices. There is a line "prices = Shoppe::DeliveryServicePrice.joins(:delivery_service).where(:shoppe_delivery_services => {:active => true}).order(:price).for_weight(total_weight)".

I remove the prefix "Shoppe::" in that line, then solute the problem.
