### ISSUE TITLE
Exception on products_controller#index, comparison of NilClass with String failed

### ISSUE THREAD

**Issue by leftis** [tryshoppe/shoppe#320]
So it's more of an edge case. When you have two or more localisations, in my case el & en, when you change the default locale of the app, without translating the product category, shoppe retrieves the localised value from the current translation and name is nil. 

Simplest solution is on products_controller:

``` ruby
def index
  <rest_of_the_line>).sort_by { |cat,pro| cat.try(:name).to_s }
end
```

but not sure it's the best solution because if let's say i will change the default locale on the near future i would like to know which product_categories i haven't translated.

thanks

**Comment by Yomud** [comment]
Good day, leftis. Maybe you already forget about this error, but I have it now. Tried different ways to resolve it, but nothing happens. And strange that text of the error never changed. Maybe you any idea?
