### ISSUE TITLE
Pricing error on featured items on products with variations

### ISSUE THREAD

**Issue by densonclan** [tryshoppe/shoppe#326]
New products with variations showing up on home page as £0.00 despite the variations all having prices set.

See screenshow below:

![screen shot 2016-01-11 at 14 39 15](https://cloud.githubusercontent.com/assets/3440128/12236362/399d280e-b871-11e5-8450-4e3bdf4d31d1.png)

**Comment by deanperry** [comment]
It may be best if you hide the price if the product has variations?

**Comment by densonclan** [comment]
Thanks, I have done that
