### ISSUE TITLE
checkout process does not create new customer record or assign order to existing customer

### ISSUE THREAD

**Issue by densonclan** [tryshoppe/shoppe#329]
I can't see where or how I would assign an order to a customer record or create one if it does not exist.

**Comment by deanperry** [comment]
To create a customer and link it to an order you can do this:

```ruby
customer = Shoppe::Customer.create first_name: "test"
current_order.customer_id = customer.id
```

**Comment by densonclan** [comment]
I have tried the following in my orders controller in the checkout action:

      customer = Shoppe::Customer.create email: @order.email_address
      current_order.customer_id = customer.id

but no customer was created. Also I would need to add some checking to see if the email address is in the customer table and if so, user that id rather than create a new one.

**Comment by densonclan** [comment]
When I look at the parameters, customer_id is not there:

Request

Parameters:

{"utf8"=>"✓",
 "_method"=>"patch",
 "authenticity_token"=>"CgKRkThtF53PjZbYA04Zm+2iODkPb4JbSdkbHN/Gq1WXVE9qg71mWMZIJs4IngG+TjnlkiEauXIHdMXBejfRUA==",
 "order"=>{"first_name"=>"sgsdfgsdfg",
 "last_name"=>"sdfgsdfgsdf",
 "company"=>"",
 "email_address"=>"barry.denson@gaskandhawley.com",
 "phone_number"=>"334634563456",
 "billing_address1"=>"sertdfg",
 "billing_address3"=>"sdfgsfdgs",
 "billing_address4"=>"dfgsdfgsg",
 "billing_postcode"=>"sdfgdsfg",
 "billing_country_id"=>"77",
 "separate_delivery_address"=>"0",
 "delivery_name"=>" ",
 "delivery_address1"=>"",
 "delivery_address3"=>"",
 "delivery_address4"=>"",
 "delivery_postcode"=>"",
 "delivery_country_id"=>"3"}}

**Comment by densonclan** [comment]
This is my full code snippet

  def checkout
    @order = Shoppe::Order.find(current_order.id)
    if request.patch?
      @order.attributes = params[:order].permit(:first_name, :last_name, :company, :billing_address1, :billing_address2, :billing_address3, :billing_address4, :billing_country_id, :billing_postcode, :email_address, :phone_number, :delivery_name, :delivery_address1, :delivery_address2, :delivery_address3, :delivery_address4, :delivery_postcode, :delivery_country_id, :separate_delivery_address, :customer_id)
      @order.ip_address = request.ip
      if Shoppe::Customer.where(email: @order.email_address).present?
        customer = Shoppe::Customer.find_by_email @order.email_address
       else 
        customer = Shoppe::Customer.create email: @order.email_address
     end 
      current_order.customer_id = customer.id.break
      if @order.proceed_to_confirm
        redirect_to checkout_payment_path
      end
    end
  end

**Comment by deanperry** [comment]
Yep it won't be in the form output as it's being submitted in the controller for security. If you look in the Shoppe admin, that order should be linked to that customer

**Comment by densonclan** [comment]
No, the order is not linked in the admin interface, nor is a customer created in the admin interface.

**Comment by deanperry** [comment]
Phone is also required so you'd need that in order for it to create the customer - https://github.com/tryshoppe/shoppe/blob/master/app/models/shoppe/customer.rb#L13

**Comment by densonclan** [comment]
Ah, quite right, I hadn't spotted that. 

It now creates customer records corrrectly but how do I link the customer_id to the order?

**Comment by densonclan** [comment]
This is now resolved. Thanks
