### ISSUE TITLE
API documentation link in Readme / Shoppe Website broken

### ISSUE THREAD

**Issue by bewatts** [tryshoppe/shoppe#337]
When I click the API documentation link it sends me here: https://s.adamcooke.io/files/

And given that [this](https://s.adamcooke.io/files/2015/V2lNaSK1w0.txt) file contains the following: 
```
Password: dmMtAmyqbVkutifMcgng8hQmniU6VB
```
It probably shouldn't be public.  

Are there real api docs somewhere I'm not seeing?

**Comment by deanperry** [comment]
The API site is working fine for me - http://api.tryshoppe.com

**Comment by bewatts** [comment]
Oh weird, when I opened the link on my home laptop, I got redirected, but on a different machine, it sends me to the correct link.  Probably something wrong on my end.

**Comment by deanperry** [comment]
Not sure, maybe @adamcooke quickly fixed it!
