### ISSUE TITLE
Unable to Turn off Demo Mode

### ISSUE THREAD

**Issue by atbyrd** [tryshoppe/shoppe#339]
Whenever I try to change demo mode to disabled I get the error  

> You cannot make changes to settings in demo mode. Sorry about that

This happens on my local machine as well as heroku. There doesn't appear to be any clues in the log.

**Comment by lukeheuer** [comment]
My guess is it's more counterintuitive design than a bug. It'd be sketchy for a demo user to be able to switch a demo store to live mode. Manually disabling demo mode through console should take care of it.

**Comment by deanperry** [comment]
Yep, @lukeheuer is correct. You'd have to manually disable demo mode in the console or directly in the database.
