### ISSUE TITLE
HTML tags in product descriptions

### ISSUE THREAD

**Issue by dznicol** [tryshoppe/shoppe#341]
Hi,

I am having trouble putting HTML tags (eg. p, br tags etc) into product descriptions.

Is this supported? I am wondering if I am doing something wrong.

Thanks in advance,

David

**Comment by densonclan** [comment]
I use <br/> tags in all my products and it works fine for me. HTML tags dont work in product names (and possibly short descriptions too).

**Comment by svenyurgensson** [comment]
@dznicol  you may use markdown syntax

**Comment by deanpcmad** [comment]
I believe Markdown can be used but in your application you'd need to render that output using .html_safe or raw

**Comment by dznicol** [comment]
Sorry yeah I should have updated ... I forgot to use .html_safe

Thanks for the reply.

I will close.

David
