### ISSUE TITLE
Error creating variants with seed

### ISSUE THREAD

**Issue by densonclan** [tryshoppe/shoppe#355]
I have the following code in db/seeds.rb

```
    pro = Shoppe::Product.find_by_sql "select id from 'shoppe_products' where sku = 'hen-blk-yel';"
    v = pro.variants.create(name: 'Vest Top Small', sku: 'hen-blk-yel-v-small', permalink: 'hen-blk-yel-v-small', price: 14.99, cost_price: 5, weight: 0.200, stock_control: false)
    v.save!
```

but when I run rake db:seed I get

   `NoMethodError: undefined method 'variants' for [#< Shoppe::Product id: 24 >]:Array`

**Comment by deanperry** [comment]
With Rails you don't need to write the SQL code out. You can just use Shoppe::Product.find_by!(sku: "text")

**Comment by densonclan** [comment]
Many thanks, my stupid error!
