### ISSUE TITLE
Status of the shoppe project

### ISSUE THREAD

**Issue by dwkns** [tryshoppe/shoppe#360]
I've been evaluating Rails based e-commerce solutions for an upcoming project. Shoppe looks ideal however I have some concerns about the project, getting help and support and the community around it.

The [Google mailing list ](https://groups.google.com/forum/#!forum/shoppe-talk) has very little activity and there hasn't been an answer to a question for about a year.

The [blog](http://blog.tryshoppe.com/) is a dead link.

The [Twitter Feed ](http://twitter.com/tryshoppe) has only one tweet on it.

The [commercial support](https://tryshoppe.com/support/commercial) doesn't seem to link anywhere. 

There are a few sporadic answers to queries within these issues (which I appreciate is not really the right place for questions on how to do things). 

It feels like Shoppe was created for a specific purpose and then open sourced as a bit of a side project. That development is done only really to aid its original use, rather than as a true open source project. And that it's not actually in use in many real world situations.

Don't misunderstand I'm not criticising this approach, it's a very generous thing to open source something that you have created. And I totally understand that the time it takes to answer give help and support (especially to newbies) is hard to come by. 

I'm just trying to understand that if we do choose to use Shoppe then to a large extent we should assume that we are on our own and that help and support isn't available (even paid). 

Can any of the project owners shed some light on the situation with Shoppe and any future plans for it?

**Comment by densonclan** [comment]
I have posted issues and got answers within 1-2 days

**Comment by deanperry** [comment]
Hey, I understand your concerns. It might be best to bring @adamcooke in to answer as he's the creator 🙂

**Comment by adamcooke** [comment]
I have no future plans for Shoppe at the moment. As you've mentioned, we built it for our own use. I haven't, personally, had the time to do any work on it. In light of that, I can't guarantee where it will go in the future at the moment.

I would say that it is best used by someone with experience who is able to debug any issues themselves.
