### ISSUE TITLE
Ability to add new fields to forms

### ISSUE THREAD

**Issue by daltonrenaldo** [tryshoppe/shoppe#362]
I believe it would be beneficial if we were able to "extend" templates. Before I explain, here is some background: 
I am using shoppe for digital downloads, I plan to package my modifications as a gem once I'm done with my project.
I need to add new fields to the product form, but there's no way to currently do that besides copy paste, and overriding the whole form. I would much prefer if there was a way to pass the extra fields to the form. For example adding a yield at the end of all the forms: 

```haml
= yield :extra_fields
```
and people creating extensions could simply do something like: 
```ruby
# app/views/shoppe/products/_modified_form.html.haml
- content_for :extra_fields do
  -# fields here
= render :partial => "shoppe/products/form"
```
or maybe even something like: 
```ruby
# app/views/shoppe/products/_modified_form.html.haml
= render :layout => "shoppe/products/form" do
  -# extra fields here
```

I am not sure if this would be the best way, but it certain beats copying the whole template just to add stuff to it.
Another way I was thinking could be the way the `Shoppe.settings` work. If we could have things like 
`Shoppe.product_form.groups`, etc... thoughts?

**Comment by deanpcmad** [comment]
Orders have a properties option which is a key value store if this helps?

**Comment by deanpcmad** [comment]
But as for custom fields this currently isn't possible unless you create some partials to create or update the properties key value store. You can see this in use with the shoppe-stripe gem as it stores the stripe token with the order
