### ISSUE TITLE
Shoppe core auto-completion?

### ISSUE THREAD

**Issue by deb0rian** [tryshoppe/shoppe#365]
Hi,

I see that RubyMine doesn't recognise Shoppe global object and doesn't auto completes anything, it's very hard to develop when you're not familiar with the system yet, switching to API docs and lurking is pretty daunting. 

Is there an auto-completion stubs or way to configure RubyMine?

Thanks

**Comment by deanpcmad** [comment]
I'm afraid I've not used RubyMine before so I'm not sure

**Comment by deb0rian** [comment]
What is your IDE for Ruby where auto-completion works?

**Comment by deanpcmad** [comment]
I use Sublime Text so I just use the standard auto completion
