### ISSUE TITLE
NameError: uninitialized constant Shoppe

### ISSUE THREAD

**Issue by Fancy7777** [tryshoppe/shoppe#366]
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        rake aborted!
remote:        NameError: uninitialized constant Shoppe
remote:        /tmp/build_2aa5de4c7995f291cd4af11b1dd5e2e0/config/routes.rb:2:in `block in <top (required)>'
remote:        /tmp/build_2aa5de4c7995f291cd4af11b1dd5e2e0/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:432:in `instance_exec'
remote:        /tmp/build_2aa5de4c7995f291cd4af11b1dd5e2e0/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:432:in `eval_block'
remote:        /tmp/build_2aa5de4c7995f291cd4af11b1dd5e2e0/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:410:in `draw'
remote:        /tmp/build_2aa5de4c7995f291cd4af11b1dd5e2e0/config/routes.rb:1:in `<top (required)>'
remote:        /tmp/build_2aa5de4c7995f291cd4af11b1dd5e2e0/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
remote:        /tmp/build_2aa5de4c7995f291cd4af11b1dd5e2e0/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application/routes_reloader.rb:40:in `each'
remote:        /tmp/build_2aa5de4c7995f291cd4af11b1dd5e2e0/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application/routes_reloader.rb:40:in `load_paths'
remote:        /tmp/build_2aa5de4c7995f291cd4af11b1dd5e2e0/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application/routes_reloader.rb:16:in `reload!'
remote:        /tmp/build_2aa5de4c7995f291cd4af11b1dd5e2e0/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application/routes_reloader.rb:26:in `block in updater'
remote:        /tmp/build_2aa5de4c7995f291cd4af11b1dd5e2e0/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/file_update_checker.rb:75:in `call'
remote:        /tmp/build_2aa5de4c7995f291cd4af11b1dd5e2e0/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/file_update_checker.rb:75:in `execute'
remote:        /tmp/build_2aa5de4c7995f291cd4af11b1dd5e2e0/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application/routes_reloader.rb:27:in `updater'
remote:        /tmp/build_2aa5de4c7995f291cd4af11b1dd5e2e0/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
remote:        /tmp/build_2aa5de4c7995f291cd4af11b1dd5e2e0/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
remote:        /tmp/build_2aa5de4c7995f291cd4af11b1dd5e2e0/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
remote:        /tmp/build_2aa5de4c7995f291cd4af11b1dd5e2e0/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
remote:        /tmp/build_2aa5de4c7995f291cd4af11b1dd5e2e0/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
remote:        /tmp/build_2aa5de4c7995f291cd4af11b1dd5e2e0/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
remote:        /tmp/build_2aa5de4c7995f291cd4af11b1dd5e2e0/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
remote:        /tmp/build_2aa5de4c7995f291cd4af11b1dd5e2e0/config/environment.rb:5:in `<top (required)>'
remote:        /tmp/build_2aa5de4c7995f291cd4af11b1dd5e2e0/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application.rb:328:in `require'
remote:        /tmp/build_2aa5de4c7995f291cd4af11b1dd5e2e0/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application.rb:328:in `require_environment!'
remote:        /tmp/build_2aa5de4c7995f291cd4af11b1dd5e2e0/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application.rb:457:in `block in run_tasks_blocks'
remote:        /tmp/build_2aa5de4c7995f291cd4af11b1dd5e2e0/vendor/bundle/ruby/2.2.0/gems/sprockets-rails-3.0.4/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
remote:        Tasks: TOP => environment
remote:        (See full trace by running task with --trace)
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote: 
remote:  !     Push rejected, failed to compile Ruby app
remote: 
remote: Verifying deploy...
remote: 
remote: !	Push rejected to ausscentt.
remote: 
To https://git.heroku.com/ausscentt.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/ausscentt.git'

**Comment by deanpcmad** [comment]
What does your Gemfile contain as it sounds like Shoppe isn't being required properly

**Comment by Fancy7777** [comment]
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.6'
# Use sqlite3 as the database for Active Record
gem 'pg'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'

  gem 'shoppe', '~> 1.0'
end

**Comment by Fancy7777** [comment]
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.6'
# Use sqlite3 as the database for Active Record
gem 'pg'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'

  gem 'shoppe', '~> 1.0'
end

**Comment by deanpcmad** [comment]
You've got the shoppe gem in the development group so you'll need to move that out

**Comment by Fancy7777** [comment]
That's because the site's tutorial ask me to put that in man.....why should I delete it when I want to use it?

发自我的 iPhone

> 在 2016年3月17日，23:07，Dean Perry <notifications@github.com> 写道：
> 
> You've got the shoppe gem in the development group so you'll need to move that out
> 
> Sent from my iPhone
>

**Comment by deanpcmad** [comment]
It says to add it to the Gemfile but not in the development group :)

**Comment by Fancy7777** [comment]
Ehh do u mind teaching me how to change it? I'm actually new to Ruby on Rails.

发自我的 iPhone

> 在 2016年3月18日，00:05，Dean Perry <notifications@github.com> 写道：
> 
> It says to add it to the Gemfile but not in the development group :)
> 
> Sent from my iPhone
>

**Comment by Fancy7777** [comment]
It's been done! thank you for the help. Didn't notice before.
