### ISSUE TITLE
Shoppe on El Capitan

### ISSUE THREAD

**Issue by moannuo** [tryshoppe/shoppe#368]
Hello,
I have some issues running Shoppe on OS X El Capitan.
Ruby 2.0.0
Rails 4.2.6
Shoppe 1.1.2

When I'm running the `rails server`, I go to `http://localhost:3000/shoppe` but I got: We're sorry, but something went wrong. If you are the application owner check the logs for more information.

So I looked at the logs and I noticed these:
```bash
Started GET "/shoppe" for ::1 at 2016-03-18 11:20:24 +0100
Processing by Shoppe::DashboardController#home as HTML
  Shoppe::Setting Load (0.1ms)  SELECT "shoppe_settings".* FROM "shoppe_settings"
Completed 500 Internal Server Error in 99ms (ActiveRecord: 0.2ms)
```

I looked over solutions on the internet but nothing went through. I guess this is an issue due to security in El Capitan. I have disabled SIP, but it's still the same thing.

Did anyone get the same issue? What should I do?

Thank you very much.

**Comment by andreavecy** [comment]
i run shoppe on teh capitan, and i have not had any problems. it is the only thing that throws you log?

**Comment by deanpcmad** [comment]
I'm running Shoppe in development on my El Capitan machine without any issues. Have you made sure you've run through the getting started tutorials? http://tryshoppe.com/docs/tutorials/getting-started
