### ISSUE TITLE
Drop blank orders on session destroy

### ISSUE THREAD

**Issue by desiderantes** [tryshoppe/shoppe#375]
Currently, Shoppe creates a blank order with a "building" status whenever a new session is created (e.g. when a user visits the site), but if the user leaves the page, the blank orders reamins on the database. This clutters the db a lot, so i guess shoppe should not save them or destroy them when the session is no longer valid.

**Comment by deanpcmad** [comment]
A script can be easily written to remove any blank orders. It wouldn't clutter the database up much as it's just creating 1 record
