### ISSUE TITLE
Couldn't find Shoppe::Order with 'id'=

### ISSUE THREAD

**Issue by tzurcan** [tryshoppe/shoppe#395]
Hi, I am new to Rails, trying to create an app as a college project using the shoppe as starting point, getting an error :
Couldn't find Shoppe::Order with 'id'= , when trying to integrate the Stripe payment following the tutorial. The error comes from below: 
def payment
 @order = Shoppe::Order.find(session[:current_order_id])
 if request.post?
 if @order.accept_stripe_token(params[:stripe_token])
 redirect_to checkout_confirmation_path
end
Any help will be highly  appreciated, Thanks

**Comment by ikhakoo** [comment]
@tzurcan 

This should fix your issue:

ApplicationController:

```
private

  def current_order
    @current_order ||= begin
      if has_order?
        @current_order
      else
        order = Shoppe::Order.create(:ip_address => request.ip)
        session[:order_id] = order.id
        order
      end
    end
  end

  def has_order?
    session[:order_id] && @current_order = Shoppe::Order.includes(:order_items => :ordered_item).find_by_id(session[:order_id])
  end
  
  helper_method :current_order, :has_order?
```

OrdersController:

```
def payment
  @order = Shoppe::Order.find(current_order.id)
  ### rest of your code here ###
end
```

**Comment by randell101** [comment]
@ikhakoo Totally worked , thanks so much man!

**Comment by tzurcan** [comment]
Thanks, i did that already and it worked for me, as well. Just wanted to know why the session one is not working, Thanks a mill
